### ISSUE TITLE
conform strictly to the Fortran2003 standard

### ISSUE THREAD

**Issue by mpbl** [geodynamics/specfem3d#10]
To make the three codes (2D, 3D_Cartesian, 3D_GLOBE) conform strictly to the Fortran standard,
we should replace all "call system(...)" statements with "call execute_command_line(...)", which is the
new standard way in Fortran2008. However, this intrinsic subroutine is currently (July 2013) not supported 
for instance by Intel ifort and thus we purposely do not do it yet, but around 2015 or so we should do it.

**Comment by komatits** [comment]
It seems all the system calls have been removed, since

grep -i "call system" src/*/*

returns nothing; thus closing this issue.
