### ISSUE TITLE
Dosen't it work with Trelis 16.3?

### ISSUE THREAD

**Issue by ZiXuanWan1994** [geodynamics/specfem3d#1001]
Hi developers， 

I have tested the script  ./Mount_StHelens/mesh_mount.py  with Trelis 16.3 . However, it failed to produced desired outputs like the figure shown in documentation and thorw off following errors：

===============================================================
Constructed 34 Free Curves: 1 to 34
Successfully opened CUBIT file '/home/wzx/public/specfem3d-master/EXAMPLES/Mount_StHelens/topo.cub'
Finished Command: open "/home/wzx/public/specfem3d-master/EXAMPLES/Mount_StHelens/topo.cub"

Trelis>healing the surface...
Trelis>Auto_clean volume 1 small_surfaces small_curve_size 10
ERROR: /home/wzx/public/specfem3d-master/EXAMPLES/Mount_StHelens/mesh_mount.py (71)
       No entity with ID 1 was found
ERROR: /home/wzx/public/specfem3d-master/EXAMPLES/Mount_StHelens/mesh_mount.py (71)
       Invalid value specified.
       Type 'modify?' for help.
Trelis>regularize volume 1
ERROR: /home/wzx/public/specfem3d-master/EXAMPLES/Mount_StHelens/mesh_mount.py (72)
       No entity with ID 1 was found

WARNING: No entities were regularized, check your input. 

relis>imprint all
WARNING: Need more than 1 body or volume to imprint.
ERROR: /home/wzx/public/specfem3d-master/EXAMPLES/Mount_StHelens/mesh_mount.py (103)
       IMPRINT operation failed
Trelis>
Trelis> exports only surfaces which will create single volume
Trelis>export acis "/home/wzx/public/specfem3d-master/EXAMPLES/Mount_StHelens/topo_2.acis" surface 3 10 12 14 15 9 ascii overwrite
ERROR: /home/wzx/public/specfem3d-master/EXAMPLES/Mount_StHelens/mesh_mount.py (106)
       No entity with ID 10 was found
ERROR: /home/wzx/public/specfem3d-master/EXAMPLES/Mount_StHelens/mesh_mount.py (106)
       No entity with ID 12 was found
ERROR: /home/wzx/public/specfem3d-master/EXAMPLES/Mount_StHelens/mesh_mount.py (106)
       No entity with ID 14 was found
ERROR: /home/wzx/public/specfem3d-master/EXAMPLES/Mount_StHelens/mesh_mount.py (106)
       No entity with ID 15 was found
ERROR: /home/wzx/public/specfem3d-master/EXAMPLES/Mount_StHelens/mesh_mount.py (106)
       No entity with ID 9 was found
Exported:   1 Surface

Trelis>
#creating new volume, this will take another 2 min...
Trelis>create volume surface all heal
Preserving undo information...done
 Healing the combined volume...
Healed the combined volume to 100% good geometry.
ERROR: /home/wzx/public/specfem3d-master/EXAMPLES/Mount_StHelens/mesh_mount.py (129)
       Failing because resulting body has no volume.
      Examine your set of surfaces to make sure
      there are no gaps and none are overlapping.
      Another possible problem is that the size of
      the resulting volume is smaller than what
      ACIS allows.
ERROR: /home/wzx/public/specfem3d-master/EXAMPLES/Mount_StHelens/mesh_mount.py (129)
       New volume creation failed.
Trelis>
Trelis># backup
Trelis>save as "/home/wzx/public/specfem3d-master/EXAMPLES/Mount_StHelens/topo_3.cub" overwrite

Trelis>
ERROR: /home/wzx/public/specfem3d-master/EXAMPLES/Mount_StHelens/mesh_mount.py (199)
       Entity not found.
ERROR: /home/wzx/public/specfem3d-master/EXAMPLES/Mount_StHelens/mesh_mount.py (199)
       No entity with ID 12 was found
ERROR: /home/wzx/public/specfem3d-master/EXAMPLES/Mount_StHelens/mesh_mount.py (199)
       No entity with ID 12 was found
ERROR: /home/wzx/public/specfem3d-master/EXAMPLES/Mount_StHelens/mesh_mount.py (199)
       No entity with ID 12 was found
ERROR: /home/wzx/public/specfem3d-master/EXAMPLES/Mount_StHelens/mesh_mount.py (199)
       Syntax error.
       Entity list entered incorrectly.
       Type 'help surface' for correct syntax.
ERROR: /home/wzx/public/specfem3d-master/EXAMPLES/Mount_StHelens/mesh_mount.py (199)
       No entity with ID 1 was found
ERROR: /home/wzx/public/specfem3d-master/EXAMPLES/Mount_StHelens/mesh_mount.py (199)
       No entity with ID 1 was found
ERROR: /home/wzx/public/specfem3d-master/EXAMPLES/Mount_StHelens/mesh_mount.py (199)
       Syntax error.
       Entity list entered incorrectly.
       Type 'help volume' for correct syntax.
WARNING: No entities specified or entities don't exist
Trelis>
Trelis># time stamp
Trelis>

Trelis>
done meshing...
Trelis>
Trelis>#backup
Trelis>save as "/home/wzx/public/specfem3d-master/EXAMPLES/Mount_StHelens/topo_4.cub" overwrite

Exported:   1 Surface

Successfully saved CUBIT file 'topo_4.cub'
Finished Command: save as "/home/wzx/public/specfem3d-master/EXAMPLES/Mount_StHelens/topo_4.cub" overwrite

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/wzx/public/specfem3d-master/CUBIT_GEOCUBIT/geocubitlib/boundary_definition.py", line 347, in define_bc
    absorbing_surf,abs_xmin,abs_xmax,abs_ymin,abs_ymax,top_surf,bottom_surf,xmin,ymin,xmax,ymax=define_surf(ip=ip,cpuxmin=cpuxmin,cpuxmax=cpuxmax,cpuymin=cpuymin,cpuymax=cpuymax,cpux=cpux,cpuy=cpuy)
  File "/home/wzx/public/specfem3d-master/CUBIT_GEOCUBIT/geocubitlib/boundary_definition.py", line 190, in define_surf
    _,_,_,_,_,top_surf=get_v_h_list(list_vol,chktop=False)
  File "/home/wzx/public/specfem3d-master/CUBIT_GEOCUBIT/geocubitlib/utilities.py", line 445, in get_v_h_list
    k=surf_or[0]
IndexError: list index out of range
Trelis>
Trelis>
Trelis>
Trelis>block 1 name "elastic 1" 
ERROR: /home/wzx/public/specfem3d-master/EXAMPLES/Mount_StHelens/mesh_mount.py (219)
       No entity with ID 1 was found
ERROR: /home/wzx/public/specfem3d-master/EXAMPLES/Mount_StHelens/mesh_mount.py (219)
       No entities specified.
Trelis>block 1 attribute count 6
ERROR: /home/wzx/public/specfem3d-master/EXAMPLES/Mount_StHelens/mesh_mount.py (220)
       No entity with ID 1 was found
ERROR: /home/wzx/public/specfem3d-master/EXAMPLES/Mount_StHelens/mesh_mount.py (220)
       No entities specified.
Trelis>block 1 attribute index 1 1
ERROR: /home/wzx/public/specfem3d-master/EXAMPLES/Mount_StHelens/mesh_mount.py (221)
       No entity with ID 1 was found
ERROR: /home/wzx/public/specfem3d-master/EXAMPLES/Mount_StHelens/mesh_mount.py (221)
       No entities specified.
Trelis>block 1 attribute index 2 2800
ERROR: /home/wzx/public/specfem3d-master/EXAMPLES/Mount_StHelens/mesh_mount.py (222)
       No entity with ID 1 was found
ERROR: /home/wzx/public/specfem3d-master/EXAMPLES/Mount_StHelens/mesh_mount.py (222)
       No entities specified.
Trelis>block 1 attribute index 3 1500
ERROR: /home/wzx/public/specfem3d-master/EXAMPLES/Mount_StHelens/mesh_mount.py (223)
       No entity with ID 1 was found
ERROR: /home/wzx/public/specfem3d-master/EXAMPLES/Mount_StHelens/mesh_mount.py (223)
       No entities specified.
Trelis>block 1 attribute index 4 2300
ERROR: /home/wzx/public/specfem3d-master/EXAMPLES/Mount_StHelens/mesh_mount.py (224)
       No entity with ID 1 was found
ERROR: /home/wzx/public/specfem3d-master/EXAMPLES/Mount_StHelens/mesh_mount.py (224)
       No entities specified.
Trelis>block 1 attribute index 5 150.0
ERROR: /home/wzx/public/specfem3d-master/EXAMPLES/Mount_StHelens/mesh_mount.py (225)
       No entity with ID 1 was found
ERROR: /home/wzx/public/specfem3d-master/EXAMPLES/Mount_StHelens/mesh_mount.py (225)
       No entities specified.
Trelis>block 1 attribute index 6 0 
ERROR: /home/wzx/public/specfem3d-master/EXAMPLES/Mount_StHelens/mesh_mount.py (226)
       No entity with ID 1 was found
ERROR: /home/wzx/public/specfem3d-master/EXAMPLES/Mount_StHelens/mesh_mount.py (226)
       No entities specified.
Trelis>
Trelis> optional saves backups
Trelis>export mesh "/home/wzx/public/specfem3d-master/EXAMPLES/Mount_StHelens/top.e" dimension 3 overwrite
ERROR: /home/wzx/public/specfem3d-master/EXAMPLES/Mount_StHelens/mesh_mount.py (229)
       No element blocks have been established!
Use the block command to assign the meshed geometry to an element block.
Or, check that the default block type is correct. Current setting: All
ERROR: /home/wzx/public/specfem3d-master/EXAMPLES/Mount_StHelens/mesh_mount.py (229)
       Could not export the data to a file.
Trelis>save as "/home/wzx/public/specfem3d-master/EXAMPLES/Mount_StHelens/meshing.cub" 

=============================================================

Some examples like  /homogeneous_halfspace_HEX8* were run successfully. So i guess Trelis 16.3 ins't supprot Specfem3d fully. 
Is that right?  Can someone give some explanations?
I’m looking forward your reply！

**Comment by casarotti** [comment]
Can you test
https://github.com/geodynamics/specfem3d/tree/devel/CUBIT_GEOCUBIT/examples/topography_models
?

**Comment by ZiXuanWan1994** [comment]
I have tested examples/topography_models.When i run the script creat_mesh.py , exception occured:

======================================================================
4) FINALIZING AND EXPORTING

..............................

"No valid composites can be created from the specified curves."           is NOT a critical ERROR.
Journaled Command: compress all

Traceback (most recent call last):
  File "create_mesh.py", line 18, in <module>
    mesh_volume.mesh(cfg)
  File "/home/wzx/public/specfem3d-devel/CUBIT_GEOCUBIT/geocubitlib/mesh_volume.py", line 44, in mesh
    mesh_layercake_regularmap(filename=filename)
  File "/home/wzx/public/specfem3d-devel/CUBIT_GEOCUBIT/geocubitlib/mesh_volume.py", line 105, in mesh_layercake_regularmap
    vol[id_vol].intervalv = cfg.iv_interval[id_vol]
IndexError: list index out of range 

=========================================================================
and there are nothing outputed except geometry_vol_0.cub&surf_vol_0.cub.  
Btw，I have updated GEOCUBIT which you submitted two months ago.
