### ISSUE TITLE
CUDA_LIB issue

### ISSUE THREAD

**Issue by hecti** [geodynamics/specfem3d#1173]
Hello, 
I would like to run some simulations using the GPU version.However when I run the configure script (./configure FC=ifort CC=icc MPIFC=mpif90 --with-cuda=yes) I get the following error:
checking linking with cudaMalloc in -lcudart... no
configure: error: CUDA library linking failed; try setting CUDA_LIB.
I have already set the paths for cuda and its libraries, and I have manually set the variable CUDA_LIB (and CUDA_LIBS as well) to /usr/local/cuda-7.5/lib64 and I keep getting the same error message. Could you please offer me some assistance with this issue?.Best,
Hector Alejandro

**Comment by komatits** [comment]
Hi,
Probably a local installation problem. (if not, please let us know)
Thanks,
Best wishes,
Dimitri.
