### ISSUE TITLE
Problem with serial decomposition of extremely big meshes, use PT-Scotch (the parallel version of SCOTCH) in SPECFEM3D instead of (or as an option in addition to) the serial version of SCOTCH

### ISSUE THREAD

**Issue by pbasini** [geodynamics/specfem3d#129]
There is a sort of bug that appears when dealing with big meshes, in my case something like 65 millions of elements: when running xdecompose_mesh I get:
```
total number of nodes:
   nnodes =     66076729
 total number of spectral elements:
   nspec =     65270709
 materials:
   num_mat =            1
   defined =            1 undefined =            0
 absorbing boundaries:
   nspec2D_xmin =       170235
   nspec2D_xmax =        60379
   nspec2D_ymin =        27992
   nspec2D_ymax =        19563
   nspec2D_bottom =       481552
   nspec2D_top =       829214
 Par_file_faults not found: assume no faults
 node valence:
   min =            1  max =           12
   nsize =           12 sup_neighbour =           70
forrtl: severe (408): fort: (3): Subscript #1 of the array ADJNCY has value -401485046 which is less than the lower bound of 0

Image              PC                Routine            Line        Source            
xdecompose_mesh    00000000004F3B5A  Unknown               Unknown  Unknown
xdecompose_mesh    00000000004F2656  Unknown               Unknown  Unknown
xdecompose_mesh    00000000004AD2A0  Unknown               Unknown  Unknown
xdecompose_mesh    0000000000475FCE  Unknown               Unknown  Unknown
xdecompose_mesh    00000000004764F1  Unknown               Unknown  Unknown
xdecompose_mesh    000000000042403F  part_decompose_me         130  part_decompose_mesh.f90
xdecompose_mesh    00000000004371B5  decompose_mesh_mp         808  decompose_mesh.F90
xdecompose_mesh    000000000045A302  MAIN__                     93  program_decompose_mesh.f90
xdecompose_mesh    0000000000403A3C  Unknown               Unknown  Unknown
libc.so.6          00002B499DBE076D  Unknown               Unknown  Unknown
xdecompose_mesh    0000000000403939  Unknown               Unknown  Unknown
```
the problem is in the term nodes_elmnts(l+j*nsize)*sup_neighbour, in line 130 of part_decompose_mesh.f90, because it exceeds the limit of 2147483646 for a 4byte integer.

With Elliot we found a temporary solution to this problem by modifying decompose_mesh.F90 and part_decompose_mesh.f90 as follows:
```
decompose_mesh.F90

integer(kind=8), dimension(:), allocatable  :: xadj
integer(kind=8) :: nb_edges
integer(kind=8) :: max_neighbour   ! real maximum number of neighbours per element
```
```
part_decompose_mesh.f90

integer(kind=8), dimension(0:nspec)  :: xadj
integer(kind=8), intent(out) :: max_neighbour
integer(kind=8)  :: i, j, k, l, m, nb_edges
integer(kind=8) :: tmp
```
As you noticed we simply redefined the kind for those variables we need, then the variable tmp will be defined three times as follows
```
tmp=int(nodes_elmnts(k+j*nsize),kind=8)*sup_neighbour+m
tmp=int(nodes_elmnts(k+j*nsize),kind=8)*sup_neighbour &
                          + xadj(nodes_elmnts(k+j*nsize))
tmp = int(nodes_elmnts(l+j*nsize), kind=8) * sup_neighbour &
                       + xadj(nodes_elmnts(l+j*nsize))
```
and will be used as the index for adjncy.

Everything seems to be fine, the code runs through this part without a problem but it's not yet time for a happy ending. In fact I get the following error:
```
total number of nodes:
   nnodes =     66076729
 total number of spectral elements:
   nspec =     65270709
 materials:
   num_mat =            1
   defined =            1 undefined =            0
 absorbing boundaries:
   nspec2D_xmin =       170235
   nspec2D_xmax =        60379
   nspec2D_ymin =        27992
   nspec2D_ymax =        19563
   nspec2D_bottom =       481552
   nspec2D_top =       829214
 Par_file_faults not found: assume no faults
 node valence:
   min =            1  max =           12
   nsize =           12 sup_neighbour =           70
 mesh2dual:
   max_neighbour =                     38
 1
ERROR: graphCheck: arc data do not match
ERROR : MAIN : Invalid check
```
This happens right after ```call scotchfgraphcheck (scotchgraph (1), ier)``` in decompose_mesh.F90. I think that this can be caused by the fact that in the previous call:
```
call scotchfgraphbuild (scotchgraph (1), 0, nspec, &
                          xadj (1), xadj (1), &
                          elmnts_load (1), xadj (1), &
                          nb_edges, adjncy (1), &
                          adjncy (1), ier)
```
among the arguments passed to scotchfgraphbuild there are also xadj and nb_edges, that are now defined with kind=8.
Temporary solution, but not sure of the results because I still have to generate the database:
```
decompose_mesh.F90
allocate(tmp_xadj(1:nspec+1),stat=ier)
if( ier /= 0 ) stop 'error allocating array xadj'
```
then, instead of calling scotchfgraphbuild, I first make sure that nb_edges is smaller than the 4bit limit and then I translate the variables defined as kind=8 into kind=4, and I pass those new variables to scotchfgraphbuild:
```
if( nb_edges < 2147483646 )then
      tmp_edges=int(nb_edges,kind=4)
      tmp_xadj=int(xadj,kind=4)

      call scotchfgraphbuild (scotchgraph (1), 0, nspec, &
                          tmp_xadj (1), tmp_xadj (1), &
                          elmnts_load (1), tmp_xadj (1), &
                          tmp_edges, adjncy (1), &
                          adjncy (1), ier)
```
As I said, I am not sure this could fix the whole thing: on the cluster (scinet consortium) even if I ask a node with 64 Gb of RAM I cannot pass through the ```scotchfgraphpart (scotchgraph (1), nparts, scotchstrat(1),part(1),ier)``` call because of lack in memory. On my workstation xdecompose_mesh runs and finishes without errors but it creates the proc000000_Database of 5.5 Gb and all the others of 300 bytes.

**Comment by komatits** [comment]
For very large meshes the serial domain decomposer runs out of memory because of the size of the connectivity table on a single machine, and that is independent of the operating system.

The clean solution is to use a parallel domain decomposer (PT-Scotch or ParMetis) instead of their serial version (Scotch or Metis); that is planned but will take a few months.

In the meantime something worth testing (and easy to test) is to use Metis instead of Scotch, you can easily replace the call to Scotch with a call to Metis. The call to Metis (off by default) is at line 925 of file src/decompose_mesh/decompose_mesh.F90 . That calls Metis through Scotch (Scotch has an internal way of doing nothing and calling Metis instead), if that fails as well then try calling Metis directly (i.e. download Metis and replace that line with a real call to Metis).
If that fails then it is the adjacency table (arrays "xadj" and "adjncy") that is too big and then there is nothing we can do with the serial version.

**Comment by komatits** [comment]
Vadim Monteiller @vmont is almost done implementing the new parallel mesh decomposer, he will commit it in the next few days.

**Comment by komatits** [comment]
Done! (parallel mesh decomposer created by Vadim Monteiller @vmont )
