### ISSUE TITLE
Does the current SPECFEM3D version still require that the fault edges remain closed during the construction in Cubit/Trelis?

### ISSUE THREAD

**Issue by mingdeyu** [geodynamics/specfem3d#1325]
Dear Dimitri,

I am now trying to construct my own fault geometries in Trelis/Cubit. I read from the manual that the fault edges (except for the one on the free surface) must be set closed in Cubit. However, as I check some fault examples, I found that some examples have fault edges opened. For instance, in TPV5, the fault edges on the top and bottom surfaces are opened (i.e., the nodes on the edge curves are not attaching each other). A similar situation happens in TPV103. In addition, in splay_faults example, the edges of faults on y_max and y_min boundary surfaces remain opened. I tried to run SPECFEM3D in TPV5 and found that it goes without errors. Therefore, I am wondering if the current version of SPECFEM3D still requires that the edges of faults must stay closed?

Many Thanks!

Deyu

**Comment by jpampuero** [comment]
Fault edges that are inside the domain should be closed.
Fault edges on the free surface should be open.
Fault edges on absorbing boundaries can be either open or closed. (Right, @snsomala ?)

**Comment by snsomala** [comment]
Yes,you are right , Pablo.  Unless; I’m in touch with the ligo folks here
in India.

Best regards,
Surendra.
