### ISSUE TITLE
How to specify input files for kinematic faults?

### ISSUE THREAD

**Issue by mingdeyu** [geodynamics/specfem3d#1326]
Dear JP @jpampuero,

I am trying to understand how to use SPECFEM3D to implement simulation with kinematic faults. However, I cannot find instructions in the manual and any examples in the repository. It seems that the manual and examples in the repository only describe how to set up the inputs files (e.g., Par_file_faults) for dynamic faults. Therefore, could you please let me know how to specify Par_file_faults and other input files in the kinematic case? If there are examples available, it would be great.

Best,

Deyu

**Comment by mingdeyu** [comment]
Thank you JP. So for the kinematic case, during the mesh generation process do we still need to create fault surfaces (i.e., split nodes) in Cubit?

**Comment by mingdeyu** [comment]
Hi JP, sorry for keep asking. I am very interested in simulating kinematic sources using a list of moment tensor point sources. If I use this approach, I assume Par_file_faults is no longer needed?

Besides, when I use a list of CMTs to represent kinematic sources, how can I define the rupture times (i.e., the sequential order of ruptures in time) of the point sources? 

If you have any documents or examples that you can share with me on this case, that would be great!

**Comment by jpampuero** [comment]
1. Correct.
2. I have never done it myself.

**Comment by mingdeyu** [comment]
Hi Emanuele,

Thank you so much for the help. But I cannot find the attachment under your comments... Thanks!

Deyu

**Comment by mingdeyu** [comment]
Thank you so much for the help!

**Comment by zhaojingxuan1028** [comment]
Hello, I would like to ask a question, In the examples are vertical faults, could you please provide the inclined fault example.

**Comment by jpampuero** [comment]
There is one example with dipping faults in EXAMPLES/fault_examples/splay_faults

**Comment by jxhxb** [comment]
> 在 EXAMPLES/fault_examples/splay_faults 中有一个带有浸渍错误的示例

Hi,I am working about seting a  30m*30m fault (with strike angle and dip angle) and the  whole module is no more than 200m*200m*200m. I tried to change the examples in “km” scale to "m" scale ,  but failed many times. I want to know if the specfem3d' fault example could finish my module simulation after some small change ? If its ok, could you tell me how it change, I just want the fault dynamic to get a seismic data. Thank you very much!

The following is my module(in "km" scale) ,it has a strike angle and dip angle. 
![image](https://github.com/user-attachments/assets/f2ba9bfc-09ae-4bfe-9218-5624d2970499)
I also calculated the stations' positon and initial_stress' positons ,and i tried to change these positions to the HETE_fault_propertise, when strike 90 and dip 90 mymoldule is working and it can get a correct result. But when strike !=90 and dip !=90, it do not  work. In this trying, i want to kown how to change strike angle and dip angle.
