### ISSUE TITLE
cuda 10 problem

### ISSUE THREAD

**Issue by shmamadking** [geodynamics/specfem3d#1327]
I had installed cuda10. I compiled specfem3d package with GPU mode on, but when i make all i got following errors
[error.txt](https://github.com/geodynamics/specfem3d/files/2860836/error.txt)
I use following command to configure :
 ./configure --with-cuda=cuda10 CUDA_LIB=/usr/local/cuda/lib64
As much as i figure out from make file , the Makefile is written to support until cuda 9. am i right?

My GPU‌ information : 
[GPU_info.txt](https://github.com/geodynamics/specfem3d/files/2860901/GPU_info.txt)

I almost know nothing about gpu please help me 
Thanks

**Comment by EtienneBachmann** [comment]
I know it is confusing but this flag "=cuda10" is not intended to specify the cuda version you are actually using, but the GPU generation you use. You should look into the "Makefile.in" to find details about how to choose this flag. If you have a Pascal for instance, you should compile using "--with-cuda=cuda8", even if you are using the CUDA 10 version.

**Comment by danielpeter** [comment]
Etienne is right, your GPU info shows that you're using a GeForce GTX 1080 Ti card. that's a Pascal architecture, which was introduced with CUDA version 8. 
try: --with-cuda=cuda8

**Comment by shmamadking** [comment]
So much thanks to all
it worked and i  could compile all code but when i run solver it gives so many same error :
Error in setConst_hprime_xx: invalid device symbol
The problem is maybe -arch sm_13 instead of -arch sm_11 in the Makefile, please doublecheck

**Comment by shmamadking** [comment]
problem solved 
it was my mistake i comment a line before in makefile 
again thanks a lot
this is my first time using github issues 
nice place

**Comment by brioglade** [comment]
Error in setConst_hprime_xx: invalid device symbol 

The problem is maybe -arch sm_13 instead of -arch sm_11 in the Makefile, please doublecheck

hi, which line should I uncomment in the makefile?  I have the same problem with cuda12.2.
