### ISSUE TITLE
absolute z in cmtsolution

### ISSUE THREAD

**Issue by casarotti** [geodynamics/specfem3d#1352]
Hi all,

I have a planar finite fault as multiple CMTSOLUTION file.
the depths of these cmtsolutions are absolute (so they are the actual z values in the mesh coordinates).

According to my understanding, this line (adding the topo to the depth) is always executed
https://github.com/geodynamics/specfem3d/blob/42abac6d18e4c3c55129d3801486e5bb000f67b0/src/specfem3D/get_elevation.f90#L131
so the final result is not a planar fault but a proxy of the topography on the fault.

is it correct? is there any way to assign the absolute z in the cmtsolution?

thanks
Emanuele

**Comment by danielpeter** [comment]
hi Emanuele,

how about line 66 in that file:
https://github.com/geodynamics/specfem3d/blob/42abac6d18e4c3c55129d3801486e5bb000f67b0/src/specfem3D/get_elevation.f90#L66

try setting in your Par_file:
USE_SOURCES_RECEIVERS_Z = .true.

that one should use absolute z values. please note that it applies to both, sources (CMTSOLUTION -> depth) and receiver (STATIONS -> burial depth) positions.

best,
daniel

**Comment by casarotti** [comment]
hi Daniel,

ok I had missed the "return" at line 73

Thanks!!!
Emanuele
