### ISSUE TITLE
Adjoint simulation issue

### ISSUE THREAD

**Issue by flpap** [geodynamics/specfem3d#1358]
Hello,

I have been trying to run the adjoint simulation (type 2) to visualize the backpropagation of the wavefield from a receiver (data obtained from forward simulation) but I have been encountering some issues. The model used is just a very simple elastic half-space with one source and one receiver.

For the master version of the code, the adjoint simulation (type 2) is crashing if dt is too high (although still below the Maximum suggested time step). If I lower dt it runs fine but the adjoint simulation outputs seem to be zero for both time series recorded at the original source but also for the visualization of backpropagating wavefield.
I was able to visualize the backpropagating wavefield using simulation type 3 but I am only interested in simulating the adjoint wavefield for now, not computing the kernels.

I have then tried the developer version of the code instead, simulation type 2 seems to be working better as I am able to visualize the backpropagating wavefield for the exact same simulation. However, at the end of the adjoint simulation run, there is the following statement.

At line 114 of file src/specfem3D/finalize_simulation.f90
Fortran runtime error: Attempt to DEALLOCATE unallocated 'number_adjsources_global'
At line 114 of file src/specfem3D/finalize_simulation.f90
Fortran runtime error: Attempt to DEALLOCATE unallocated 'number_adjsources_global'
At line 114 of file src/specfem3D/finalize_simulation.f90
Fortran runtime error: Attempt to DEALLOCATE unallocated 'number_adjsources_global'
At line 114 of file src/specfem3D/finalize_simulation.f90
Fortran runtime error: Attempt to DEALLOCATE unallocated 'number_adjsources_global'
At line 114 of file src/specfem3D/finalize_simulation.f90At line 114 of file src/specfem3D/finalize_simulation.f90
Fortran runtime error: Attempt to DEALLOCATE unallocated 'number_adjsources_global'
Fortran runtime error: Attempt to DEALLOCATE unallocated 'number_adjsources_global'
At line 114 of file src/specfem3D/finalize_simulation.f90
Fortran runtime error: Attempt to DEALLOCATE unallocated 'number_adjsources_global'
At line 114 of file src/specfem3D/finalize_simulation.f90
Fortran runtime error: Attempt to DEALLOCATE unallocated 'number_adjsources_global'

Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.

At line 114 of file src/specfem3D/finalize_simulation.f90
Fortran runtime error: Attempt to DEALLOCATE unallocated 'number_adjsources_global'
At line 114 of file src/specfem3D/finalize_simulation.f90
Fortran runtime error: Attempt to DEALLOCATE unallocated 'number_adjsources_global'

mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

Process name: [[20711,1],9]
Exit code:    2

 
Any advice?

Thank you

Florian

**Comment by danielpeter** [comment]
thanks for checking and catching! the deallocation should be fixed now by PR #1359. please just update to the newest devel version.

**Comment by flpap** [comment]
Thanks a lot ! Working fine now
Best,
Florian
