### ISSUE TITLE
problem with compiling mesh2vtu

### ISSUE THREAD

**Issue by shmamadking** [geodynamics/specfem3d#1377]
Hi there 

I want to use mesh2vtu util but when I tried to compile it I received errors that some include file are missing. They are :
vtkPolyDataSource.h
vtkProcessObject.h
vtkUnstructuredGridToPolyDataFilter.h
I already installed vtk-9.0.0 but these .h files are exist missing. 
So I found that files on the web and downloaded them (for example for file vtkPolyDataSource.h I download it from this address https://vtk.org/doc/release/5.6/html/a04711.html ) and put them in related include directory (/usr/include/vtk-9.0/).
After that I face with following errors during making files:
```

In file included from /usr/include/vtk-9.0/vtkPolyDataSource.h:19,
                 from /usr/include/vtk-9.0/vtkUnstructuredGridToPolyDataFilter.h:18,
                 from mesh2vtu.cxx:44:
/usr/include/vtk-9.0/vtkProcessObject.h:22:46: error: expected initializer before ‘:’ token
   22 |  class VTK_FILTERING_EXPORT vtkProcessObject : public vtkAlgorithm
      |                                              ^
In file included from /usr/include/vtk-9.0/vtkUnstructuredGridToPolyDataFilter.h:18,
                 from mesh2vtu.cxx:44:
/usr/include/vtk-9.0/vtkPolyDataSource.h:24:36: error: expected initializer before ‘:’ token
   24 |  class VTK_COMMON_EXPORT vtkSource : public vtkProcessObject
      |                                    ^
In file included from mesh2vtu.cxx:44:
/usr/include/vtk-9.0/vtkUnstructuredGridToPolyDataFilter.h:22:65: error: expected initializer before ‘:’ token
   22 |  class VTK_FILTERING_EXPORT vtkUnstructuredGridToPolyDataFilter : public vtkPolyDataSource
      |                                                                 ^
mesh2vtu.cxx: In function ‘int main(int, char**)’:
mesh2vtu.cxx:130:13: error: ‘class vtkXMLUnstructuredGridWriter’ has no member named ‘SetInput’; did you mean ‘GetInput’?
  130 |   writer -> SetInput(dataSet);
      |             ^~~~~~~~
      |             GetInput
make: *** [Makefile:24: mesh2vtu.o] Error 1

```

It seems that this include files were in older versions of VTK (like version 5.6) but I can't find and install that old versions.
I am using opensuse leap 15.1

**Comment by danielpeter** [comment]
right, the mesh2vtu needs probably some old VTK version. unfortunately, VTK installations are often a bit complicated, so that becomes tricky. i will see how to update it.

as a workaround, just try to use the `bin/xcombine_vol_data_vtk` tool to output directly VTK-format files. then there is no need to use mesh2vtu at all.

**Comment by shmamadking** [comment]
Thanks again for your help. 
I thought that  xcombine_vol_data_vtk combine vtk files and xcombine_vol_data combines .bin files. That was my misunderstanding. 
so much thanks.
