### ISSUE TITLE
SU output files

### ISSUE THREAD

**Issue by anderl-uk** [geodynamics/specfem3d#1387]
We are trying to use the SU output option of specfem3D but can't read the traces with SU. In matlab the traces look fine however. Is there any converting to be done before reading the files with SU? Thanks!

**Comment by danielpeter** [comment]
you might have to use `suoldtonew`. to test this, try something like:
```
suoldtonew <OUTPUT_FILES/0_dz_SU | suxwigb 
```

**Comment by danielpeter** [comment]
in case the above doesn't work, there might also be a fix in PR #1391 which could help with SU file outputs. thus, see if the most recent devel version will fix the issue.
