### ISSUE TITLE
compilation error with xmeshfem

### ISSUE THREAD

**Issue by chaindl** [geodynamics/specfem3d#1392]
Hello!

I am getting the following error when compiling xmeshfem3D:

```
src/meshfem3D/read_value_mesh_parameters.f90:157:0:

  157 |     string_read = string_read(index_equal_sign + 1:len_trim(string_read))
      | 
Error: ‘__builtin_memmove’ reading 512 bytes from a region of size 510 [-Werror=stringop-overflow=]
```

xspecfem3D and xgenerate_databases compile without any errors, though. I have just updated gcc from version 9 to version 10, but to no avail.

Thank you for your help!

**Comment by danielpeter** [comment]
can you try with the devel branch version and report the error together with your compiler version and compilation flags used?

**Comment by chaindl** [comment]
Oh, the devel branch version works! And I just saw that the instructions in the pdf manual say to download the devel version. I was following the instructions on the CIG website.

**Comment by chaindl** [comment]
Thank you for the quick response! Brilliant support!

**Comment by danielpeter** [comment]
thanks for your feedback.
