### ISSUE TITLE
examples in EXAMPLES/fault_example can not work

### ISSUE THREAD

**Issue by loycbt** [geodynamics/specfem3d#1394]
Dear all, 

I tried to generate meshing file using tpv5.py, tpv15, etc. in EXAMPLES/fault_example, it didn't work. The errors are as follow when tpv5 was loaded in trelis16.5: 

ERROR: G:/specfem3d/MESHING/TPV5/TPV5.py (139)
       No entity with ID 2 was found
ERROR: G:/specfem3d/MESHING/TPV5/TPV5.py (139)
       No entities specified.
ERROR: G:/specfem3d/MESHING/TPV5/TPV5.py (139)
       No entity with ID 2 was found
ERROR: G:/specfem3d/MESHING/TPV5/TPV5.py (139)
       No entities specified.
ERROR: G:/specfem3d/MESHING/TPV5/TPV5.py (139)
       No entity with ID 3 was found
ERROR: G:/specfem3d/MESHING/TPV5/TPV5.py (139)
       No entities specified.
ERROR: G:/specfem3d/MESHING/TPV5/TPV5.py (139)
       No entity with ID 3 was found
ERROR: G:/specfem3d/MESHING/TPV5/TPV5.py (139)
       No entities specified.

And similar problems also appear in tpv15, tpv16.

**Comment by jpampuero** [comment]
This could be a problem with how Trelis assigns IDs to objects in a mesh. 
Were you calling the python script from inside the Trelis GUI, or from your shell (outside Trelis)?
If you were doing the former, please try the latter.
If that does not solve the issue, please post your complete log file.

**Comment by loycbt** [comment]
Dear jpampuero,
Actually, I only know how to call the python script from the Trelis GUI, and there will be "No module named cubit" if I run it from the shell.

**Comment by jpampuero** [comment]
Does the error occur also if you run the script only once and right after opening the Trelis GUI ?

**Comment by loycbt** [comment]
Yes.

**Comment by jpampuero** [comment]
Please upload the complete log file.

**Comment by loycbt** [comment]
This is all the information obtained from the command line of trelis:


Group 'nf' deleted (group id = 1492).
Finished Command: delete group 1492

Group 'nf' deleted (group id = 1493).
Finished Command: delete group 1493

Group 'nf' deleted (group id = 1494).
Finished Command: delete group 1494

Group 'nf' deleted (group id = 1495).
Finished Command: delete group 1495

Group 'nf' deleted (group id = 1496).
Finished Command: delete group 1496

Group 'nf' deleted (group id = 1497).
Finished Command: delete group 1497

Group 'nf' deleted (group id = 1498).
Finished Command: delete group 1498

Group 'nf' deleted (group id = 1499).
Finished Command: delete group 1499

Group 'nf' deleted (group id = 1500).
Finished Command: delete group 1500

Group 'nf' deleted (group id = 1501).
Finished Command: delete group 1501

Group 'nf' deleted (group id = 1502).
Finished Command: delete group 1502

Group 'nf' deleted (group id = 1503).
Finished Command: delete group 1503

Group 'nf' deleted (group id = 1504).
Finished Command: delete group 1504

Group 'nf' deleted (group id = 1505).
Finished Command: delete group 1505

Group 'nf' deleted (group id = 1506).
Finished Command: delete group 1506

Group 'nf' deleted (group id = 1507).
Finished Command: delete group 1507

Group 'nf' deleted (group id = 1508).
Finished Command: delete group 1508

Group 'nf' deleted (group id = 1509).
Finished Command: delete group 1509

Group 'nf' deleted (group id = 1510).
Finished Command: delete group 1510

Group 'nf' deleted (group id = 1511).
Finished Command: delete group 1511

Group 'nf' deleted (group id = 1512).
Finished Command: delete group 1512

Group 'nf' deleted (group id = 1513).
Finished Command: delete group 1513

Group 'nf' deleted (group id = 1514).
Finished Command: delete group 1514

Group 'nf' deleted (group id = 1515).
Finished Command: delete group 1515

Group 'nf' deleted (group id = 1516).
Finished Command: delete group 1516

Group 'nf' deleted (group id = 1517).
Finished Command: delete group 1517

Group 'nf' deleted (group id = 1518).
Finished Command: delete group 1518

Group 'nf' deleted (group id = 1519).
Finished Command: delete group 1519

Group 'nf' deleted (group id = 1520).
Finished Command: delete group 1520

Group 'nf' deleted (group id = 1521).
Finished Command: delete group 1521

Group 'nf' deleted (group id = 1522).
Finished Command: delete group 1522

Group 'nf' deleted (group id = 1523).
Finished Command: delete group 1523

Group 'nf' deleted (group id = 1524).
Finished Command: delete group 1524

Group 'nf' deleted (group id = 1525).
Finished Command: delete group 1525

Group 'nf' deleted (group id = 1526).
Finished Command: delete group 1526

Group 'nf' deleted (group id = 1527).
Finished Command: delete group 1527

Group 'nf' deleted (group id = 1528).
Finished Command: delete group 1528

Group 'nf' deleted (group id = 1529).
Finished Command: delete group 1529

Group 'nf' deleted (group id = 1530).
Finished Command: delete group 1530

Group 'nf' deleted (group id = 1531).
Finished Command: delete group 1531

Group 'nf' deleted (group id = 1532).
Finished Command: delete group 1532

Group 'nf' deleted (group id = 1533).
Finished Command: delete group 1533

Group 'nf' deleted (group id = 1534).
Finished Command: delete group 1534

Group 'nf' deleted (group id = 1535).
Finished Command: delete group 1535

Group 'nf' deleted (group id = 1536).
Finished Command: delete group 1536

Group 'nf' deleted (group id = 1537).
Finished Command: delete group 1537

Group 'nf' deleted (group id = 1538).
Finished Command: delete group 1538

Group 'nf' deleted (group id = 1539).
Finished Command: delete group 1539

Group 'nf' deleted (group id = 1540).
Finished Command: delete group 1540

Group 'nf' deleted (group id = 1541).
Finished Command: delete group 1541

Group 'nf' deleted (group id = 1542).
Finished Command: delete group 1542

Group 'nf' deleted (group id = 1543).
Finished Command: delete group 1543

Group 'nf' deleted (group id = 1544).
Finished Command: delete group 1544

Group 'nf' deleted (group id = 1545).
Finished Command: delete group 1545

Group 'nf' deleted (group id = 1546).
Finished Command: delete group 1546

Group 'nf' deleted (group id = 1547).
Finished Command: delete group 1547

Group 'nf' deleted (group id = 1548).
Finished Command: delete group 1548

Group 'nf' deleted (group id = 1549).
Finished Command: delete group 1549

Group 'nf' deleted (group id = 1550).
Finished Command: delete group 1550

Group 'nf' deleted (group id = 1551).
Finished Command: delete group 1551

Group 'nf' deleted (group id = 1552).
Finished Command: delete group 1552

Group 'nf' deleted (group id = 1553).
Finished Command: delete group 1553

Group 'nf' deleted (group id = 1554).
Finished Command: delete group 1554

Group 'nf' deleted (group id = 1555).
Finished Command: delete group 1555

Group 'nf' deleted (group id = 1556).
Finished Command: delete group 1556

Group 'nf' deleted (group id = 1557).
Finished Command: delete group 1557

Group 'nf' deleted (group id = 1558).
Finished Command: delete group 1558

Group 'nf' deleted (group id = 1559).
Finished Command: delete group 1559

Group 'nf' deleted (group id = 1560).
Finished Command: delete group 1560

Group 'nf' deleted (group id = 1561).
Finished Command: delete group 1561

Group 'nf' deleted (group id = 1562).
Finished Command: delete group 1562

Group 'nf' deleted (group id = 1563).
Finished Command: delete group 1563

Group 'nf' deleted (group id = 1564).
Finished Command: delete group 1564

Group 'nf' deleted (group id = 1565).
Finished Command: delete group 1565

Group 'nf' deleted (group id = 1566).
Finished Command: delete group 1566

Group 'nf' deleted (group id = 1567).
Finished Command: delete group 1567

Group 'nf' deleted (group id = 1568).
Finished Command: delete group 1568

Group 'nf' deleted (group id = 1569).
Finished Command: delete group 1569

Group 'nf' deleted (group id = 1570).
Finished Command: delete group 1570

Group 'nf' deleted (group id = 1571).
Finished Command: delete group 1571

Group 'nf' deleted (group id = 1572).
Finished Command: delete group 1572

Group 'nf' deleted (group id = 1573).
Finished Command: delete group 1573

Group 'nf' deleted (group id = 1574).
Finished Command: delete group 1574

Group 'nf' deleted (group id = 1575).
Finished Command: delete group 1575

Group 'nf' deleted (group id = 1576).
Finished Command: delete group 1576

Group 'nf' deleted (group id = 1577).
Finished Command: delete group 1577

Group 'nf' deleted (group id = 1578).
Finished Command: delete group 1578

Group 'nf' deleted (group id = 1579).
Finished Command: delete group 1579

Group 'nf' deleted (group id = 1580).
Finished Command: delete group 1580

Group 'nf' deleted (group id = 1581).
Finished Command: delete group 1581

Group 'nf' deleted (group id = 1582).
Finished Command: delete group 1582

Group 'nf' deleted (group id = 1583).
Finished Command: delete group 1583

Group 'nf' deleted (group id = 1584).
Finished Command: delete group 1584

Group 'nf' deleted (group id = 1585).
Finished Command: delete group 1585

Group 'nf' deleted (group id = 1586).
Finished Command: delete group 1586

Group 'nf' deleted (group id = 1587).
Finished Command: delete group 1587

Group 'nf' deleted (group id = 1588).
Finished Command: delete group 1588

Group 'nf' deleted (group id = 1589).
Finished Command: delete group 1589

Group 'nf' deleted (group id = 1590).
Finished Command: delete group 1590

Group 'nf' deleted (group id = 1591).
Finished Command: delete group 1591

Group 'nf' deleted (group id = 1592).
Finished Command: delete group 1592

Group 'nf' deleted (group id = 1593).
Finished Command: delete group 1593

Group 'nf' deleted (group id = 1594).
Finished Command: delete group 1594

Group 'nf' deleted (group id = 1595).
Finished Command: delete group 1595

Group 'nf' deleted (group id = 1596).
Finished Command: delete group 1596

Group 'nf' deleted (group id = 1597).
Finished Command: delete group 1597

Group 'nf' deleted (group id = 1598).
Finished Command: delete group 1598

Group 'nf' deleted (group id = 1599).
Finished Command: delete group 1599

Group 'nf' deleted (group id = 1600).
Finished Command: delete group 1600

Group 'nf' deleted (group id = 1601).
Finished Command: delete group 1601

Group 'nf' deleted (group id = 1602).
Finished Command: delete group 1602

Group 'nf' deleted (group id = 1603).
Finished Command: delete group 1603

Group 'nf' deleted (group id = 1604).
Finished Command: delete group 1604

Group 'nf' deleted (group id = 1605).
Finished Command: delete group 1605

Group 'nf' deleted (group id = 1606).
Finished Command: delete group 1606

Group 'nf' deleted (group id = 1607).
Finished Command: delete group 1607

Group 'nf' deleted (group id = 1608).
Finished Command: delete group 1608

Group 'nf' deleted (group id = 1609).
Finished Command: delete group 1609

Group 'nf' deleted (group id = 1610).
Finished Command: delete group 1610

Group 'nf' deleted (group id = 1611).
Finished Command: delete group 1611

Group 'nf' deleted (group id = 1612).
Finished Command: delete group 1612

Group 'nf' deleted (group id = 1613).
Finished Command: delete group 1613

Group 'nf' deleted (group id = 1614).
Finished Command: delete group 1614

Group 'nf' deleted (group id = 1615).
Finished Command: delete group 1615

Group 'nf' deleted (group id = 1616).
Finished Command: delete group 1616

Group 'nf' deleted (group id = 1617).
Finished Command: delete group 1617

Group 'nf' deleted (group id = 1618).
Finished Command: delete group 1618

Group 'nf' deleted (group id = 1619).
Finished Command: delete group 1619

Group 'nf' deleted (group id = 1620).
Finished Command: delete group 1620

Group 'nf' deleted (group id = 1621).
Finished Command: delete group 1621

Group 'nf' deleted (group id = 1622).
Finished Command: delete group 1622

Group 'nf' deleted (group id = 1623).
Finished Command: delete group 1623

Group 'nf' deleted (group id = 1624).
Finished Command: delete group 1624

Group 'nf' deleted (group id = 1625).
Finished Command: delete group 1625

Group 'nf' deleted (group id = 1626).
Finished Command: delete group 1626

Group 'nf' deleted (group id = 1627).
Finished Command: delete group 1627

Group 'nf' deleted (group id = 1628).
Finished Command: delete group 1628

Group 'nf' deleted (group id = 1629).
Finished Command: delete group 1629

Group 'nf' deleted (group id = 1630).
Finished Command: delete group 1630

Group 'nf' deleted (group id = 1631).
Finished Command: delete group 1631

Group 'nf' deleted (group id = 1632).
Finished Command: delete group 1632

Group 'nf' deleted (group id = 1633).
Finished Command: delete group 1633

Group 'nf' deleted (group id = 1634).
Finished Command: delete group 1634

Group 'nf' deleted (group id = 1635).
Finished Command: delete group 1635

Group 'nf' deleted (group id = 1636).
Finished Command: delete group 1636

Group 'nf' deleted (group id = 1637).
Finished Command: delete group 1637

Group 'nf' deleted (group id = 1638).
Finished Command: delete group 1638

Group 'nf' deleted (group id = 1639).
Finished Command: delete group 1639

Group 'nf' deleted (group id = 1640).
Finished Command: delete group 1640

Group 'nf' deleted (group id = 1641).
Finished Command: delete group 1641

Group 'nf' deleted (group id = 1642).
Finished Command: delete group 1642

Group 'nf' deleted (group id = 1643).
Finished Command: delete group 1643

Group 'nf' deleted (group id = 1644).
Finished Command: delete group 1644

Group 'nf' deleted (group id = 1645).
Finished Command: delete group 1645

Group 'nf' deleted (group id = 1646).
Finished Command: delete group 1646

Group 'nf' deleted (group id = 1647).
Finished Command: delete group 1647

Group 'nf' deleted (group id = 1648).
Finished Command: delete group 1648

Group 'nf' deleted (group id = 1649).
Finished Command: delete group 1649

Group 'nf' deleted (group id = 1650).
Finished Command: delete group 1650

Group 'nf' deleted (group id = 1651).
Finished Command: delete group 1651

Group 'nf' deleted (group id = 1652).
Finished Command: delete group 1652

Group 'nf' deleted (group id = 1653).
Finished Command: delete group 1653

Group 'nf' deleted (group id = 1654).
Finished Command: delete group 1654

Group 'nf' deleted (group id = 1655).
Finished Command: delete group 1655

Group 'nf' deleted (group id = 1656).
Finished Command: delete group 1656

Group 'nf' deleted (group id = 1657).
Finished Command: delete group 1657

Group 'nf' deleted (group id = 1658).
Finished Command: delete group 1658

Group 'nf' deleted (group id = 1659).
Finished Command: delete group 1659

Group 'nf' deleted (group id = 1660).
Finished Command: delete group 1660

Group 'nf' deleted (group id = 1661).
Finished Command: delete group 1661

Group 'nf' deleted (group id = 1662).
Finished Command: delete group 1662

Group 'nf' deleted (group id = 1663).
Finished Command: delete group 1663

Group 'nf' deleted (group id = 1664).
Finished Command: delete group 1664

Group 'nf' deleted (group id = 1665).
Finished Command: delete group 1665

Group 'nf' deleted (group id = 1666).
Finished Command: delete group 1666

Group 'nf' deleted (group id = 1667).
Finished Command: delete group 1667

Group 'nf' deleted (group id = 1668).
Finished Command: delete group 1668

Group 'nf' deleted (group id = 1669).
Finished Command: delete group 1669

Group 'nf' deleted (group id = 1670).
Finished Command: delete group 1670

Group 'nf' deleted (group id = 1671).
Finished Command: delete group 1671

Group 'nf' deleted (group id = 1672).
Finished Command: delete group 1672

Group 'nf' deleted (group id = 1673).
Finished Command: delete group 1673

Group 'nf' deleted (group id = 1674).
Finished Command: delete group 1674

Group 'nf' deleted (group id = 1675).
Finished Command: delete group 1675

Group 'nf' deleted (group id = 1676).
Finished Command: delete group 1676

Group 'nf' deleted (group id = 1677).
Finished Command: delete group 1677

Group 'nf' deleted (group id = 1678).
Finished Command: delete group 1678

Group 'nf' deleted (group id = 1679).
Finished Command: delete group 1679

Group 'nf' deleted (group id = 1680).
Finished Command: delete group 1680

Group 'nf' deleted (group id = 1681).
Finished Command: delete group 1681

Group 'nf' deleted (group id = 1682).
Finished Command: delete group 1682

Group 'nf' deleted (group id = 1683).
Finished Command: delete group 1683

Group 'nf' deleted (group id = 1684).
Finished Command: delete group 1684

Group 'nf' deleted (group id = 1685).
Finished Command: delete group 1685

Group 'nf' deleted (group id = 1686).
Finished Command: delete group 1686

Group 'nf' deleted (group id = 1687).
Finished Command: delete group 1687

Group 'nf' deleted (group id = 1688).
Finished Command: delete group 1688

Group 'nf' deleted (group id = 1689).
Finished Command: delete group 1689

Group 'nf' deleted (group id = 1690).
Finished Command: delete group 1690

Group 'nf' deleted (group id = 1691).
Finished Command: delete group 1691

Group 'nf' deleted (group id = 1692).
Finished Command: delete group 1692

Group 'nf' deleted (group id = 1693).
Finished Command: delete group 1693

Group 'nf' deleted (group id = 1694).
Finished Command: delete group 1694

Group 'nf' deleted (group id = 1695).
Finished Command: delete group 1695

Group 'nf' deleted (group id = 1696).
Finished Command: delete group 1696

Group 'nf' deleted (group id = 1697).
Finished Command: delete group 1697

Group 'nf' deleted (group id = 1698).
Finished Command: delete group 1698

Group 'nf' deleted (group id = 1699).
Finished Command: delete group 1699

Group 'nf' deleted (group id = 1700).
Finished Command: delete group 1700

Group 'nf' deleted (group id = 1701).
Finished Command: delete group 1701

Group 'nf' deleted (group id = 1702).
Finished Command: delete group 1702

Group 'nf' deleted (group id = 1703).
Finished Command: delete group 1703

Group 'nf' deleted (group id = 1704).
Finished Command: delete group 1704

Group 'nf' deleted (group id = 1705).
Finished Command: delete group 1705

Group 'nf' deleted (group id = 1706).
Finished Command: delete group 1706

Group 'nf' deleted (group id = 1707).
Finished Command: delete group 1707

Group 'nf' deleted (group id = 1708).
Finished Command: delete group 1708

Group 'nf' deleted (group id = 1709).
Finished Command: delete group 1709

Group 'nf' deleted (group id = 1710).
Finished Command: delete group 1710

Group 'nf' deleted (group id = 1711).
Finished Command: delete group 1711

Group 'nf' deleted (group id = 1712).
Finished Command: delete group 1712

Group 'nf' deleted (group id = 1713).
Finished Command: delete group 1713

Group 'nf' deleted (group id = 1714).
Finished Command: delete group 1714

Group 'nf' deleted (group id = 1715).
Finished Command: delete group 1715

Group 'nf' deleted (group id = 1716).
Finished Command: delete group 1716

Group 'nf' deleted (group id = 1717).
Finished Command: delete group 1717

Group 'nf' deleted (group id = 1718).
Finished Command: delete group 1718

Group 'nf' deleted (group id = 1719).
Finished Command: delete group 1719

Group 'nf' deleted (group id = 1720).
Finished Command: delete group 1720

Group 'nf' deleted (group id = 1721).
Finished Command: delete group 1721

Group 'nf' deleted (group id = 1722).
Finished Command: delete group 1722

Group 'nf' deleted (group id = 1723).
Finished Command: delete group 1723

Group 'nf' deleted (group id = 1724).
Finished Command: delete group 1724

Group 'nf' deleted (group id = 1725).
Finished Command: delete group 1725

Group 'nf' deleted (group id = 1726).
Finished Command: delete group 1726

Group 'nf' deleted (group id = 1727).
Finished Command: delete group 1727

Group 'nf' deleted (group id = 1728).
Finished Command: delete group 1728

Group 'nf' deleted (group id = 1729).
Finished Command: delete group 1729

Group 'nf' deleted (group id = 1730).
Finished Command: delete group 1730

Group 'nf' deleted (group id = 1731).
Finished Command: delete group 1731

Group 'nf' deleted (group id = 1732).
Finished Command: delete group 1732

Group 'nf' deleted (group id = 1733).
Finished Command: delete group 1733

Group 'nf' deleted (group id = 1734).
Finished Command: delete group 1734

Group 'nf' deleted (group id = 1735).
Finished Command: delete group 1735

Group 'nf' deleted (group id = 1736).
Finished Command: delete group 1736

Group 'nf' deleted (group id = 1737).
Finished Command: delete group 1737

Group 'nf' deleted (group id = 1738).
Finished Command: delete group 1738

Group 'nf' deleted (group id = 1739).
Finished Command: delete group 1739

Group 'nf' deleted (group id = 1740).
Finished Command: delete group 1740

Group 'nf' deleted (group id = 1741).
Finished Command: delete group 1741

Group 'nf' deleted (group id = 1742).
Finished Command: delete group 1742

Group 'nf' deleted (group id = 1743).
Finished Command: delete group 1743

Group 'nf' deleted (group id = 1744).
Finished Command: delete group 1744

Group 'nf' deleted (group id = 1745).
Finished Command: delete group 1745

Group 'nf' deleted (group id = 1746).
Finished Command: delete group 1746

Group 'nf' deleted (group id = 1747).
Finished Command: delete group 1747

Group 'nf' deleted (group id = 1748).
Finished Command: delete group 1748

Group 'nf' deleted (group id = 1749).
Finished Command: delete group 1749

Group 'nf' deleted (group id = 1750).
Finished Command: delete group 1750

Group 'nf' deleted (group id = 1751).
Finished Command: delete group 1751

Group 'nf' deleted (group id = 1752).
Finished Command: delete group 1752

Group 'nf' deleted (group id = 1753).
Finished Command: delete group 1753

Group 'nf' deleted (group id = 1754).
Finished Command: delete group 1754

Group 'nf' deleted (group id = 1755).
Finished Command: delete group 1755

Group 'nf' deleted (group id = 1756).
Finished Command: delete group 1756

Group 'nf' deleted (group id = 1757).
Finished Command: delete group 1757

Group 'nf' deleted (group id = 1758).
Finished Command: delete group 1758

Group 'nf' deleted (group id = 1759).
Finished Command: delete group 1759

Group 'nf' deleted (group id = 1760).
Finished Command: delete group 1760

Group 'nf' deleted (group id = 1761).
Finished Command: delete group 1761

Group 'nf' deleted (group id = 1762).
Finished Command: delete group 1762

Group 'nf' deleted (group id = 1763).
Finished Command: delete group 1763

Group 'nf' deleted (group id = 1764).
Finished Command: delete group 1764

Group 'nf' deleted (group id = 1765).
Finished Command: delete group 1765

Trelis>
Trelis>#  FOR THE BULK (Seismic wave propagation part for SPECFEM3D)
Trelis>
Trelis>###### This is boundary_definition.py of GEOCUBIT
Trelis>#..... which extracts the bounding faces and defines them into blocks
Trelis>#entities=['face'] # this is a deprecated boundary definition function
Trelis>#boundary_definition.define_bc(entities,parallel=True)
Trelis>
Trelis>
Trelis>
##boundary box: 
##  x min: -21000.0
##  y min: -21000.0
##  z min: -21000.0
##  x max: 21000.0
##  y max: 21000.0
##  z max: 0.0
##boundary box: 
##  x length: 42000.0
##  y length: 42000.0
##  z length: 21000.0
center_point[2]-21000.0
kz:1
Finished Command: block 1 hex in volume 1

Finished Command: block 1 name "vol1"

ERROR: E:/specfem3d-master/MESHING/tpv5/TPV5.py (139)
       No entity with ID 2 was found
ERROR: E:/specfem3d-master/MESHING/tpv5/TPV5.py (139)
       No entities specified.
ERROR: E:/specfem3d-master/MESHING/tpv5/TPV5.py (139)
       No entity with ID 2 was found
ERROR: E:/specfem3d-master/MESHING/tpv5/TPV5.py (139)
       No entities specified.
ERROR: E:/specfem3d-master/MESHING/tpv5/TPV5.py (139)
       No entity with ID 3 was found
ERROR: E:/specfem3d-master/MESHING/tpv5/TPV5.py (139)
       No entities specified.
ERROR: E:/specfem3d-master/MESHING/tpv5/TPV5.py (139)
       No entity with ID 3 was found
ERROR: E:/specfem3d-master/MESHING/tpv5/TPV5.py (139)
       No entities specified.
['face']
##entity: face
Finished Command: block 2 face in surface 5

Finished Command: block 2 name "face_abs_xmin"

Finished Command: block 3 face in surface 3

Finished Command: block 3 name "face_abs_xmax"

Finished Command: block 4 face in surface 2

Finished Command: block 4 name "face_abs_ymin"

Finished Command: block 5 face in surface 4

Finished Command: block 5 name "face_abs_ymax"

Finished Command: block 6 face in surface 1

Finished Command: block 6 name "face_abs_bottom"

Finished Command: block 7 face in surface 8

Finished Command: block 7 name "face_topo"

Trelis>
Trelis>#### Define material properties for the 2 volumes ################
Trelis>#### DEFINE MATERIAL PROPERTIES #######################
Trelis>
Trelis># Material properties in concordance with tpv5 benchmark.
Trelis>
Trelis>block 1 name "elastic 1" 
Finished Command: block 1 name "elastic 1"

Trelis>block 1 attribute count 6
Number of attributes on block 1 changed from default to 6
Finished Command: block 1 attribute count 6

Trelis>block 1 attribute index 1 1
Finished Command: block 1 attribute index 1 1

Trelis>block 1 attribute index 2 6000
Finished Command: block 1 attribute index 2 6000

Trelis>block 1 attribute index 3 3464
Finished Command: block 1 attribute index 3 3464

Trelis>block 1 attribute index 4 2670
Finished Command: block 1 attribute index 4 2670

Trelis>block 1 attribute index 5 13
Finished Command: block 1 attribute index 5 13

Trelis>block 1 attribute index 6 0
Finished Command: block 1 attribute index 6 0

Trelis>
Trelis>#### Export to SPECFEM3D format using cubit2specfem3d.py of GEOCUBIT
Trelis>
Trelis>
HEX Blocks:
block  1 material flag  1
Absorbing Boundary Conditions:
bc  2 bc flag  4
bc  3 bc flag  4
bc  4 bc flag  4
bc  5 bc flag  4
bc  6 bc flag  4
bc  7 bc flag  4
Topography (free surface)
7
Free surface
None
Preserving undo information...done
Finished Command: compress all

Turning informational messages off.
Writing MESH/mesh_file..... v2
 total number of elements: 37212
block  1  hexes  37212
Ok
Writing MESH/materials_file.....
block  1 flag  1
Ok
Writing MESH/nodes_coords_file.....
  number of nodes: 41228
Ok
Writing MESH/free_or_absorbing_surface_file_zmax.....
free surface (topography) block name: face_topo id: 7
  number of faces =  1772
Ok
Echoing has been turned ON
Finished Command: set echo on

Turning informational messages off.
  block name: face_abs_xmin id: 2
xmin
  number of faces =  882
Ok
  block name: face_abs_xmax id: 3
xmax
  number of faces =  882
Ok
  block name: face_abs_ymin id: 4
ymin
  number of faces =  882
Ok
  block name: face_abs_ymax id: 5
ymax
  number of faces =  882
Ok
  block name: face_abs_bottom id: 6
bottom
  number of faces =  1772
Ok
Echoing has been turned ON
Finished Command: set echo on

Writing MESH/nummaterial_velocity_file.....
number of material: 1
Ok
Turning informational messages on.
Finished Command: set info on

Echoing has been turned ON
Finished Command: set echo on

END SPECFEM3D exporting process......
Trelis>
Trelis># all files needed by SCOTCH are now in directory MESH
Trelis>
Trelis>
Trelis>

**Comment by danielpeter** [comment]
no worries, those errors won't affect the mesh. they come from temporary sheet bodies that have been created for the fault surfaces. the errors pop up when looking for the boundaries of the mesh, trying to check out elements from those sheet bodies as well.

**Comment by jpampuero** [comment]
@loycbt do you get correct mesh files despite these error messages?

**Comment by loycbt** [comment]
Thank you for your help. Yes, there are no error messages. But the generated mesh cannot work in specfem3d, and it hints that



STOP Inconsistent fault mesh: corresponding node in the other fault face was not found

  running database generation on  4 processors...

 rank            0 - Error opening file: ./OUTPUT_FILES/DATABASES_MPI/proc000000_Database
 please make sure file exists
 Error opening database file
 Error detected, aborting MPI... proc            0
 rank            1 - Error opening file: ./OUTPUT_FILES/DATABASES_MPI/proc000001_Database
 please make sure file exists
 Error opening database file
 Error detected, aborting MPI... proc            1
 rank            3 - Error opening file: ./OUTPUT_FILES/DATABASES_MPI/proc000003_Database
 please make sure file exists
 Error opening database file
 Error detected, aborting MPI... proc            3
 rank            2 - Error opening file: ./OUTPUT_FILES/DATABASES_MPI/proc000002_Database
 please make sure file exists
 Error opening database file
 Error detected, aborting MPI... proc            2

So, I think it's still the mesh problem.

**Comment by danielpeter** [comment]
could you try and see if with the updated devel version from PR #1395 the fault file gets correctly meshed?

**Comment by loycbt** [comment]
Nice. I have check it, the updated version is ok. Thank you very much.
