### ISSUE TITLE
Issues with double precision

### ISSUE THREAD

**Issue by eyalshimony** [geodynamics/specfem3d#1413]
When configured with the enable-double-precision flag, the software produces inconsistent results with different meshes. For example, in the image two vertical velocity seismograms can be seen, both in the same location (1 km deep in the model), in the same model and the simulation was produced with the same source. The only difference is the meshing - the blue on was run with 40x40x40 elements, while the orange with 80x80x80 elements. Both discretisations are fine enough to get accurate results (more than 5 points per minimum wavelength). This issues doesn't appear when the software is configured without the flag (namely, compiled with single precision)
![image](https://user-images.githubusercontent.com/80954047/111866911-67c5da80-8979-11eb-9fd3-526ca168f29b.png)

**Comment by danielpeter** [comment]
thanks for pointing this out! while looking at it, I noticed some issues with getting elevation values, but not sure if this is causing these discrepancies. 

would you have more details on how you created the mesh and what Par_file setup you used for this example? that would help me reproducing this issue.

**Comment by eyalshimony** [comment]
I created the mesh using the internal mesher in the program. The Par_file, Mesh_Par_file and interfaces file are attached (ignore the suffixes, I had to change them so GitHub will allow their upload). I attached the 80x80x80 version. The differences between it and the 40x40x40 version:
1. In the Par_file, the number of processors used is reduced to 25.
2. In the Mesh_Par_file, the number of processors in each direction is reduced to 5, the number of elements in each horizontal direction is reduced to 40, and the vertical elements numbers in the bottom of the configuration is halved (together with the horizontal number in each layer)
3. In the interfaces file, the number of elements in each layer is halved.

I will note that the same phenomenon happened also when used with a homogeneous, non-dissipative configuration.

On another note, I used UTM projection as when I turned it off (suppress_utm_projection = true) the boundary layer creation collapsed (I think it was an overflow) when used with double precision. This phenomenon can also be reproduced when running the regular_element_mesh example provided with the software (under meshfem3D_examples) with a depth block of 4 km rather than 2 km in the double precision mode. If you are looking into issues with double precision, maybe you can look also into it.

[Par_file.txt](https://github.com/geodynamics/specfem3d/files/6203151/Par_file.txt)
[interfaces.txt](https://github.com/geodynamics/specfem3d/files/6203152/interfaces.txt)
[Mesh_Par_file.txt](https://github.com/geodynamics/specfem3d/files/6203153/Mesh_Par_file.txt)

**Comment by danielpeter** [comment]
well, that was a hard nut to crack... but great to finally found out about this! 

it turns out that with your mesh dimensions, the sorting routine gets dazzled in double precision which in turn leads to an issue with the MPI interface points not being properly assigned. this is due to numerical round-offs being different in single vs. double precision and therefore point positions in one MPI slice can be at slightly different positions than in the neighboring MPI slice.  the sorting looks at these positions and in double precision was so sensitive, that these round-off differences between slices created the issue. 

well, long story short, the PR #1421 should fix this. please check and let me know if it solves your issue...  :)

**Comment by jpampuero** [comment]
Hi Daniel,
The tolerance is currently defined as a small fraction of the size of the whole domain. Given this tolerance is used to compare nodes that are close to each other or co-located, would it be better to define it as a fraction of the typical size of a spectral element?
Pablo

**Comment by danielpeter** [comment]
right, this could be an idea as well. the current fix is not a perfect solution, but should work for now.

the issue is sensitive to the dimension and location of the mesh, more than the element size. the problem starts when reading in mesh grid positions. in the above case, the mesh dimensions are:
```
 UTM X min =    709609.76051683107     
 UTM X max =    728187.32852168824     

 UTM Y min =    3453838.7764272518     
 UTM Y max =    3476410.5617065295     
```
after the MPI partitioning, different processes will get slightly different position values due to numerical rounding. let say, we have a point at some MPI interface at 34650000.00000008 and the other process reads 34650000.00000001, the sorting should have a tolerance above 10-8. 

in principle, the element size could be used to estimate the tolerance, but these round-off errors when reading in positions differ if we would have the mesh dimension between 0-20,000 m or between 3,450,000-3,470,000 m. that is, the round-off digit will be at different positions. 

maybe in future, we could consider normalizing the grid positions before this sorting and then adapt to element size.  at the moment, this just seemed to be too convoluted. using the mesh dimension for this tolerance estimation was an easy estimate to get in the code. running an element size detection loop first could take a while for large partitions.

**Comment by jpampuero** [comment]
I see.
I guess we need to add in section 6.1 of the manual (about mesh generation with split-nodes on faults) that the artificial fault opening should be larger than SMALLVAL_TOL*(Xmax-Xmin).

**Comment by danielpeter** [comment]
correct, the opening should be bigger than this value you note above (SMALLVAL_TOL is 10.d-10) otherwise the indexing routine will not properly recognize the split nodes.

**Comment by eyalshimony** [comment]
Thanks for the reply and the update, but it seems that the fix didn't work (or, more accurately, ruined stuff):
1. When generate databases is run on a model without a C-PML layer, its run is exceedingly long now: for the socal1d examples in the examples it took 22 minutes (and it was well under a minute on my server before the update). I checked it also when used in single precision it seems to take a long time there also; I didn't wait to see how much exactly, but it was over 5 minutes.
2. When generate databases is run on a model with a C-PML layer, there is a segmentation fault and it collapses.

On another note, did you happen to look into the issue with boundary layer creation collapse when used with the program used with the UTM projection turned off?

And finally, until your comment I didn't know that the most updated version of the program is on the devel branch and not the master (I used the one on the master until now); I think it may be useful to add a comment about it on the README or the manual.

**Comment by danielpeter** [comment]
this sounds like you're using debugging flags for compilation now. a reason for the excessive runtimes could be that you compiled with bounds-checking. please check and make sure you use the same compiler flags as before or something like these runtime flags in Makefile like:
```
FLAGS_CHECK = -O3 -mcmodel=medium -DFORCE_VECTORIZATION
```
that should speed up your simulations again.

regarding the segmentation fault, it would be great if you could post the details. when I run your example with PML turned on, all looks still fine.

and last, devel is the development branch which has the latest features and fixes, but might also have some new bugs introduced. the master branch is in principle the more stable one. anyway, I'll update the master version soon - hopefully with your fix included.

**Comment by eyalshimony** [comment]
Thanks for the answer. I think I accidentally compiled a wrong commit which may had problems or something like that. I re-compiled the right version now.

However, there still seems to be a problem when using a larger number of processes in parallel. I started with testing it on the socal1D example provided in the project (in the meshfem3d examples directory). After I raised the number of horizontal elements to 32 in each direction, when I did the calculations on 1 process it worked, but when I did them on 16, there was a floating point error. I attached the par file and mesh par file that produced the error; you can make it work by changing the number of processors in each direction in the mesh par file from 4 to 1 and the number of processors in the par file from 16 to 1. I will note that when using 24 elements in each direction and 9 processors in total this error does not happen. This error does also happen with larger number of processes (I tried both 25 and 100).

As for the error itself, it looks like this:

#0  0x2B776A786467
#1  0x2B776A786AAE
#2  0x2B776B21866F
#3  0x427610 in finalize_databases_ at finalize_databases.f90:52
#4  0x427F07 in MAIN__ at generate_databases.f90:259

[Mesh_Par_file.txt](https://github.com/geodynamics/specfem3d/files/6319881/Mesh_Par_file.txt)

[Par_file.txt](https://github.com/geodynamics/specfem3d/files/6319880/Par_file.txt)

Once again, thanks for all the help

**Comment by eyalshimony** [comment]
Hi,

I originally used the following configure pattern:
`./configure FC=gfortran CC=gcc MPIFC=mpif90 --with-mpi --enable-vectorization --enable-double-precision`
which resulted in the aforementioned error.

As the program doesn't allow the use of enable-vectorization with enable-debug, I used for the test you asked for the following pattern:
`./configure FC=gfortran CC=gcc MPIFC=mpif90 --with-mpi --enable-double-precision --enable-debug`
No error occurred, and the run completed successfully.

At first I suspected that maybe the error is related to the vectorization, but also the following pattern:
`./configure FC=gfortran CC=gcc MPIFC=mpif90 --with-mpi --enable-double-precision`
resulted in the very same error.

Running the program in debug mode as a solution isn't really viable as it seems to run much slower in this case, and as you see I cannot reproduce the error in debug mode. Maybe there is something in the configure pattern that you think I should change?

**Comment by danielpeter** [comment]
what gfortran version do you use:
```
gfortran -v
```

**Comment by eyalshimony** [comment]
4.8.5

**Comment by danielpeter** [comment]
could you try out with this updated PR #1428 

unfortunately, the gcc version is a bit old and I have no system available here to test it. so I'm fishing in the dark :)

**Comment by eyalshimony** [comment]
Great, everything works.
The run completes successfully now. I ran again, in double precision mode, with the two different meshes from the first message and they produced the same result.

Thanks for all the help!
