### ISSUE TITLE
Station accuracy dropped after filtered

### ISSUE THREAD

**Issue by niyiyu** [geodynamics/specfem3d#1420]
Hi!

When using SPECFEM3D for a small scale high accuracy simulation (size: X2.4km/Y2.4 km/Z0.96km), receiver position in STATIONS_FILTER may deviated from STATIONS, which will also lead to error in SU_stations_info.bin and seismogram header.

This happened when SUPPRESS_UTM_PROJECTION is true and coordinates of receivers are directly given in STATIONS (numbers are pretty large).
```
...
N1  CE  401449.28 3554845.5 0 0 
N2  CE  401448.50 3554850.5 0 0 
N3  CE  401447.75 3554855.25 0 0 
...
```

When writing filtered station info, format is given in src/specfem3D/station_filter.f90 as:

```
 99         write(IOUT,'(a10,1x,a10,4e18.6)') &
100                          trim(station_name),trim(network_name), &
101                            sngl(stlat),sngl(stlon),sngl(stele),sngl(stbur)
```

which will truncate the coordinates as:

```
...
N1  CE  0.401449E+06 0.355485E+07 0.000000+E00 0.000000+E00 
N2  CE  0.401448E+06 0.355485E+07 0.000000+E00 0.000000+E00 
N3  CE  0.401448E+06 0.355486E+07 0.000000+E00 0.000000+E00 
...
```
Note that the error can be ~5m in axis y. And this issue can be easily solved by adding output digits as:
```
 99         write(IOUT,'(a10,1x,a10,4e18.8)') &
```

Hope this note can be helpful for someone.

Yiyu

**Comment by danielpeter** [comment]
thanks for pointing out! this has been addressed in the devel version.
