### ISSUE TITLE
Cannot view combined partitions using Paraview

### ISSUE THREAD

**Issue by subedika** [geodynamics/specfem3d#1438]
Hi, I'm new to specfem3D and need some help viewing the simulations. I have successfully run the configuration script, compiled xmeshfem3D, xgenerate_databases and xspecfem3D in the SPECFEM3D directory. When I ran the `run_this_example.sh` script in EXAMPLES/meshfem3D_examples/simple_model, it successfully ran and produced the required OUTPUT_FILES and DATABASES_MPI. However, I could not find a .vtk file similar to simple_model.png provided in the /simple_model directory. The process ran on 4 MPI processors. The output log did generate a message which said 'no protocol specified' while setting up xmeshfem3D, xgenerate_databases and xspecfem3D. DATABASES_MPI do have the partitioned files for each processor. Please help me in viewing the combined .vtk file.

**Comment by danielpeter** [comment]
by default, the setup and run script of the example in simple_model/ will produce vtk-files `proc000000_vs.vtk` in DATABASES_MPI/:
```
$ ls -1 DATABASES_MPI/
proc000000_Database
..
proc000000_vp.bin
proc000000_vp.vtk
proc000000_vs.bin
proc000000_vs.vtk
..
```
the `proc***_vs.vtk` files can be loaded and visualized in Paraview. the simple_model.png picture is an example screenshot file from Paraview to check how this could look like.

**Comment by subedika** [comment]
Thanks for the clarification.
