### ISSUE TITLE
CMT convert to Cartesian basis system

### ISSUE THREAD

**Issue by brioglade** [geodynamics/specfem3d#1453]
hi
Refer to https://github.com/geodynamics/specfem3d/issues/1439

The CMTSOLUTION is always using the Harvard CMT convention:
r is up, t is south, and p is east (x = South, y = East, z = Up)
 If the SPECFEM reference frame convention is: x = North, y = East, z = Down.
Does that mean the conversion between  the CMTSOLUTION moments (Mrr/Mpp/Mtt/..) and the Cartesian representation (Mxx/Myy/Mzz/..) is as following?
To convert from CMT to SPECFEM: r -> -z, theta -> -x, phi -> y
Mzz = Mrr
Mxx = Mtt
Myy = Mpp
Mxz = Mrt
Myz = - Mrp
Mxy = - Mpt

Is it right?
Thank you very much.

**Comment by danielpeter** [comment]
the important reference frame is the r/t/p convention given in the CMTSOLUTION files: r is up, t is south, and p is east, which leads to the SPECFEM conversion: r -> z, theta -> -y, phi -> x, and moment tensor components like
```
p (longitude phi) east -> SPECFEM: Mxx = Mpp
t (co-latitude theta) south -> SPECFEM: Myy = Mtt
r (radial) up -> SPECFEM: Mzz = Mrr
Mxz = + Mrp
Myz = - Mrt
Mxy = - Mtp
```

**Comment by planetarianPKU** [comment]
Page 40 of the manual: 
For any particular earthquake, the CMTSOLUTION file that represents the point source may be obtained directly
from the Harvard Centroid-Moment Tensor (CMT) web page (www.seismology.harvard.edu). It looks like
the example shown in Fig. 5.1.
![image](https://user-images.githubusercontent.com/28781143/124858345-73004d00-dfe0-11eb-8a49-50b1e33206a4.png)
