### ISSUE TITLE
A question about the sigma values in xsmooth_sem

### ISSUE THREAD

**Issue by UM2020-create** [geodynamics/specfem3d#1463]
Hi,

   May I ask how to define appropriate SIGMA_H SIGMA_V values in xsmooth_sem? Should I use the maximum (or minimum) element size as these parameters? Or they depend on the maximum (or minimum) GLL point distance? 

    Hope to get your answer. Thanks a lot!

**Comment by danielpeter** [comment]
Smoothing is a subjective choice and in a sense similar to damping. For example, in Carl Tape's et al. 2007 paper ([https://doi.org/10.1111/j.1365-246X.2006.03191.x](https://doi.org/10.1111/j.1365-246X.2006.03191.x)), the smoothing scalelength can be estimated by
```
scalelength = sigma * sqrt(8)
```
either using horizontal `sigma_h` or vertical `sigma_v` values.

One choice is to set this scalelength around the shortest wavelength of the waves used in the measurements. Thus, you would make it dependent on your measurements. Another "sensible" choice would be to use a smoothing scalelength of around 1/4 of the dominant wavelength of your sources. 

In case you designed your mesh such that it resolves the minimum wavelength with about 5 points per wavelength, which by default makes the wavelength the size of an element, then you would want to choose the smoothing scalelength to be about the element size. To be on a safer side for your mesh resolution, you would want the shortest wavelength to be resolved by about 1.5 elements at least (assuming 4th-order elements, NGLL=5). you'll figure out the corresponding scalelength & sigma calculation for your mesh...

again, many different choices and strategies are possible though - a very subjective matter. It is typical to start with larger smoothing values and decrease them as the inversion proceeds, for example along to what Hejun Zhu's 2015 paper ([https://doi.org/10.1093/gji/ggu492](https://doi.org/10.1093/gji/ggu492)) suggests. Furthermore, horizontal smoothing is often chosen to be larger than vertical smoothing to avoid smearing out too much vertical layering in your subsurface.

**Comment by UM2020-create** [comment]
Thanks a lot for your explanation!
