### ISSUE TITLE
On the calculation of the steepest descent direction in src/tomography/get_sd_direction.f90 

### ISSUE THREAD

**Issue by ZQiwen** [geodynamics/specfem3d#1495]
Hi, 

I'm trying to do some waveform tomography studies using the specfem3d package, especially using the codes under src/tomography/. I am wondering that: 
As a discrete version of the formulas (e.g. eq. (16)) in Tromp et al. (2005), should the steepest descent direction in the code get_sd_direction.f90 be
model_dbeta(i,j,k,ispec) = - kernel_beta(i,j,k,ispec) * volumel
instead of 
model_dbeta(i,j,k,ispec) = - kernel_beta(i,j,k,ispec)
whereas the volume is the volume associated with GLL point of the index (i,j,k,ispec)?

Here is the eq. (16) from Tromp et al. (2005)
![image](https://user-images.githubusercontent.com/45736336/161283035-ccbb6f2f-070d-4999-b57a-6cda1827a432.png)

Qiwen

**Comment by danielpeter** [comment]
that's not the same. equation (16) relates to the misfit, not the model update.

please see the comment here in your PR:
https://github.com/geodynamics/specfem3d/pull/1494#issuecomment-1085985870

**Comment by ZQiwen** [comment]
Hi Daniel! 

Thanks for the response!
Yes, you are right. The kernel is already the gradient, it doesn't make any sense to multiply a volume. 
Thank you for the explanation!

Qiwen
