### ISSUE TITLE
PGV vs PVS

### ISSUE THREAD

**Issue by eikmeier-cn** [geodynamics/specfem3d#1500]
Hello everybody,

I would like to confirm that my understanding of what is stated in the manual is correct. But before that, let's see if our understanding of the terminology is the same. I understand PGV (peak ground velocity) as, within a time interval, the highest velocity value among the three components of a sensor, and PVS (peak vector sum) as, in that same time interval, the highest value of the resulting velocity vector sum of the three components.

On page 75 of the manual, version 3.0, we have, for the Par_file:
MOVIE_TYPE: if set to 1, the horizontal peak-ground values of displacement/velocity/acceleration are output. If set to 2, the maximum length of the particle displacement/velocity/acceleration vector is output. Please be aware that these peak-ground values can differ from each other.

So, the following doubts arise, considering velocity:
1) Is option 1 the maximum velocity value among the 2 horizontal components (PGV-horizontal), the 3 components (PGV) or is it the PVS?
2) Would option 2 be the maximum velocity value among the 3 horizontal components (PGV) or is it the PVS?

Thanks,

**Comment by danielpeter** [comment]
for option 1, it outputs the peak value in the Y-component (which is N-component if UTM setting is on) of the velocity field.
for option 2, it outputs the norm of the particle velocity vector.

any suggestion on modifying this output to make it more convenient for you is welcome.

**Comment by eikmeier-cn** [comment]
Thanks for the answer @danielpeter. So, I understand option 1 as a N-component PGV (or PPV - Peak Particle Velocity)  and option 2 as a PVS.
