### ISSUE TITLE
Force unit using FORCESOLUTION and USE_EXTERNAL_SOURCE_FILE

### ISSUE THREAD

**Issue by eikmeier-cn** [geodynamics/specfem3d#1505]
Hello everybody.

When I use an external displacement source file, with unit in meters, the forces inputted in the modeling are the values in the file times the "factor force source" (FORCESOLUTION)? And is Newton the force unit?

**Comment by danielpeter** [comment]
yes, that's correct.

for point sources (Par_file parameter `USE_FORCE_POINT_SOURCE` set to `.true.`), the source is specified in the `FORCESOLUTION` file with an amplitude factor:
```
factor force source:             1.d10
```
this factor is always added to the source, also in case an external source time function is used. the source strength refers in general to Newton [N]. 

however, the code is mostly unaware of units. that is, the user has to make sure the input dimensions are coherent. usually, the code assumes SI standard units (for mesh node positions given in meters, velocities in meter/seconds, etc.). still, as a user you could for example specify your mesh dimensions to be in nanometers [nm], velocities in [km/h], and then the source unit becomes less obvious.

**Comment by eikmeier-cn** [comment]
Thank you @danielpeter.
