### ISSUE TITLE
Files with long filenames in main directory

### ISSUE THREAD

**Issue by gassmoeller** [geodynamics/specfem3d#1526]
We have some files with very long filenames in the main directory, which mess up the view of some file managers. The content of the README file with long filename should be included in the main readme, or in the installation instructions. The filename `script_to_copy_all_the_initial_input_files_correctly_for_the_NUMBER_OF_SIMULTANEOUS_RUNS_option.bash` should be shortened and the current file name should be added as a comment inside the script instead.

This is a pretty easy task to take on for a first contributor! Help is welcome!

**Comment by slimkaki** [comment]
Hello! Can I be assigned to this issue?

**Comment by gassmoeller** [comment]
Solved by #1536. Thanks @slimkaki!
