### ISSUE TITLE
VTK ATTENUATION

### ISSUE THREAD

**Issue by casarotti** [geodynamics/specfem3d#169]
if ATTENUATION and USE_OLSEN with external TOMOGRAPHY are TRUE

if SAVE_MESH_FILES is true the vtk files for the attenuation are written before the definition of Q_mu so basically they show a fixed value of 9000 everywhere.

**Comment by komatits** [comment]
Hi all,
Any update on that?
Can I close the Git issue?

Thanks,
Dimitri.

**Comment by komatits** [comment]
Hi all,
Any update on that?
Can I close the Git issue?

Thanks,
Dimitri.

**Comment by komatits** [comment]
Closed the issue because I never got any answer.
