### ISSUE TITLE
it seems that there is a bug in the compute_curl_field routine for movies

### ISSUE THREAD

**Issue by kbai** [geodynamics/specfem3d#198]
In  write_movie_output.f90, line 1267-1291
do k = 1,NGLLZ
      do j = 1,NGLLY
        do i = 1,NGLLX
          ! divergence \nabla \cdot \bf{v}
          div(i,j,k,ispec) = dvxdxl(i,j,k) + dvydyl(i,j,k) + dvzdzl(i,j,k)
          ! curl
          curl_x(i,j,k,ispec) = dvzdyl(i,j,k) - dvydzl(i,j,k)
          curl_y(i,j,k,ispec) = dvxdzl(i,j,k) - dvzdxl(i,j,k)
          curl_z(i,j,k,ispec) = dvydxl(i,j,k) - dvxdyl(i,j,k)
          ! velocity field
          iglob = ibool(i,j,k,ispec)
          velocity_x(i,j,k,ispec) = veloc(1,iglob)
          velocity_y(i,j,k,ispec) = veloc(2,iglob)
          velocity_z(i,j,k,ispec) = veloc(3,iglob)

          valency(iglob)=valency(iglob)+1

          div_glob(iglob) = div_glob(iglob) + div(i,j,k,ispec)
          curl_glob(iglob)= curl_glob(iglob) &
%%%%%%problem    + 0.5_CUSTOM_REAL*(curl_x(i,j,k,ispec) &
                            + curl_x(i,j,k,ispec)+curl_x(i,j,k,ispec))
        enddo
      enddo
    enddo
  enddo !NSPEC_AB

As I marked there , curl_x the same thing was added three times. That's weird. Maybe it should be curl_x+curl_y+curl_z

**Comment by komatits** [comment]
Thanks! I got rid of "curl_glob" in the whole code, since the formula to compute it made no sense.
