### ISSUE TITLE
OpenMP support is currently broken

### ISSUE THREAD

**Issue by luet** [geodynamics/specfem3d#207]
See [build 92](http://specfem3d-buildbot.princeton.edu/builders/specfem3d_builder/builds/92/steps/--with-openmp_make/logs/stdio)

**Comment by komatits** [comment]
Could be / will be done in the context of the CAAR SUMMIT proposal. @luet @mpbl @jeroentromp

**Comment by komatits** [comment]
It seems that Seiji Tsuboi's group at JAMSTEC in Japan has fixed that and may soon commit it

**Comment by komatits** [comment]
Not really a bug... more of a missing feature (not widely requested yet)

**Comment by komatits** [comment]
Closing this, since there are currently no plans to add OpenMP support.
