### ISSUE TITLE
Bug  in xgeneratedatabes with C-PML?

### ISSUE THREAD

**Issue by m8hpw** [geodynamics/specfem3d#273]
When I use generate_databases on the mesh I made, an error "C-PML error: distance to C-PML/mesh interface is bigger than thickness of C-PML layer".  But I think it is a bug. Indeed,

In subroutine pml_set_local_dampingcoeff(myrank,xstore,ystore,zstore) of pml_set_local_dampingcoeff.f90
  ! gets abscissa of current grid point along the damping profile
                    abscissa_in_PML_x = xstore(iglob) - xoriginright
                    ! determines distance to C-PML/mesh interface
                    dist = abscissa_in_PML_x / CPML_width_x
                    ! gets damping profile at the C-PML element's GLL point
                    d_x = pml_damping_profile_l(myrank,iglob,dist,vp,CPML_width_x)

So dist is a ratio of two distances that should be between 0 and 1.

But in definition of pml_damping_profile_l in pml_set_local_dampingcoeff.f90
distance is considered as an absolute distance.
 ! checks coordinates of C-PML points and thickness of C-PML layer
  if( delta < dist ) then
     print*,'C-PML point ',iglob
     print*,'distance to C-PML/mesh interface ',dist
     print*,'C-PML thickness ',delta
     call exit_mpi(myrank,'C-PML error: distance to C-PML/mesh interface is bigger than thickness of C-PML layer')
  endif

That is why I got an error. I changed if (delta < dist) into if (dist<0 .or dist > 1.0). The code is now running. But I do not yet check if the PML layer is still effective.

M8hpw

**Comment by komatits** [comment]
Fixed by Zhinan @xiezhinan .
