### ISSUE TITLE
release a new tagged, validated version

### ISSUE THREAD

**Issue by rmodrak** [geodynamics/specfem3d#293]

**Comment by komatits** [comment]
Not sure we need tagged version any more, since the CIG web site does not mention them any more. People get either master or devel, using a Git checkout.

**Comment by rmodrak** [comment]
For professional software developers, I believe version tagging is an accepted best practice—the main advantage I think is that it forces testing and validation as well as coordination among developers.  For scientists working in a decentralized fashion though, it is probably a very hard goal to achieve. Even if it is not feasible in the foreseeable future, it may still be a good long-term goal to pay lip service to and aim for.
