### ISSUE TITLE
make create_mesh.py work

### ISSUE THREAD

**Issue by komatits** [geodynamics/specfem3d#311]
From @carltape   Using the latest version, the default example works form me. I started a separate discussion with Daniel @danielpeter about create_mesh.py, which does not work for me. But I have never used it before either.

**Comment by komatits** [comment]
Hi @carltape @danielpeter and @casarotti ,

Any update on this bug? Can I close the issue on GitHub?

Thanks,
Dimitri.

**Comment by komatits** [comment]
From Date: 	Mon, 16 Mar 2015 11:22:38 -0700
From: 	Erin Wirth Moriarty 
To @casarotti 

Hi,

Just a quick comment regarding create_mesh.py in the 
homogeneous_halfspace example under the devel branch. The final "else" 
statement (setting the material properties with use_explicit=0) seems to 
be missing cubit2specfem3d.export2SPECFEM3D('MESH/') and therefore is 
not generating all the necessary mesh files.

Erin.

**Comment by casarotti** [comment]
updated  the routine

**Comment by komatits** [comment]
Fixed by Emanuele @casarotti .
