### ISSUE TITLE
boundary_definition in CUBIT_GEOCUBIT fails on Trelis

### ISSUE THREAD

**Issue by specfem3d-zhang-ksu** [geodynamics/specfem3d#330]
the boundary_definition does not work properly to define the block and later to assign material properties to the block. Here is a history file by running the EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py. This run is on Trelis 15.01, and my python version is 2.6.6. I have not run this script on other Trelis or cubit but I was told from csimsoft.com that same thing happens on Trelis 15.1. Running other examples gets the same problem. 

********** Now playing /home/chzhang_ksu/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py **********

Trelis>#!/usr/bin/env python
Trelis>
Trelis>###########################################################################
Trelis>#### TNM: This is the mesh generation, adapted from a journal file
Trelis>####      specific to the settings of Komatitsch and Tromp 1999, Fig.8
Trelis>####      Aug 2009
Trelis>###########################################################################
Trelis>
Trelis>
Trelis>
Trelis>
Trelis>
Trelis>
Trelis>
Trelis>
Trelis>reset
Default CUBIT model file is '/home/chzhang_ksu/specfem3d/EXAMPLES/layered_halfspace/cubit01.cub'

Finished Command: reset

Trelis>brick x 134000 y 134000 z 60000
Successfully created brick volume 1
Finished Command: brick x 134000 y 134000 z 60000

Trelis>
Trelis># This seems to conflict with boundary_definition.py
Trelis># ....which leaves the model space at e.g. x=[-67,67] km
Trelis>volume 1 move x 67000 y 67000 z -30000
Finished Command: volume 1 move x 67000 y 67000 z -30000

Trelis>
Trelis># create vertices for discontinuity
Trelis>
Trelis>split curve 9  distance '+str(distance))
Preserving undo information...done
Updated volume(s): 1
Finished Command: split curve 9 distance 3000

Trelis>split curve 10  distance '+str(distance))
Preserving undo information...done
Updated volume(s): 1
Finished Command: split curve 10 distance 3000

Trelis>split curve 11  distance '+str(distance))
Preserving undo information...done
Updated volume(s): 1
Finished Command: split curve 11 distance 3000

Trelis>split curve 12  distance '+str(distance))
Preserving undo information...done
Updated volume(s): 1
Finished Command: split curve 12 distance 3000

Trelis>
Trelis># create surface for interface
Trelis># surface at 3 km depth
Trelis>create surface vertex 9 10 12 11

Creation of Surface 7 (Surface 7) Successful.
This is sheet body 2 (Body 2)
Finished Command: create surface vertex 9 10 12 11

Trelis>
Trelis>section volume 1 with surface 7 keep normal
Created volume(s): 3
SECTION successfully completed
Created volume 3
Finished Command: section volume 1 with surface 7 keep normal

Trelis>section volume 1 with surface 7 reverse
Preserving undo information...done
Updated volume(s): 1
SECTION successfully completed
Created volume 1
Finished Command: section volume 1 with surface 7 reverse

Trelis>
Trelis># create vertices for auxiliary interface to allow for refinement
Trelis>#distance = 9000
Trelis># to have a surface at 25050 m depth, such that point force source can be located exactly
Trelis># on a GLL point at that depth as in Komatitsch et al. (1999)
Trelis>
Trelis>split curve 29  distance '+str(distance))
Preserving undo information...done
Updated volume(s): 3
Finished Command: split curve 29 distance 22050

Trelis>split curve 31  distance '+str(distance))
Preserving undo information...done
Updated volume(s): 3
Finished Command: split curve 31 distance 22050

Trelis>split curve 32  distance '+str(distance))
Preserving undo information...done
Updated volume(s): 3
Finished Command: split curve 32 distance 22050

Trelis>split curve 36  distance '+str(distance))
Preserving undo information...done
Updated volume(s): 3
Finished Command: split curve 36 distance 22050

Trelis>
Trelis>
Trelis># create surface for buffer interface to refine BELOW the discontinuity
Trelis># surface at 3 km depth
Trelis>create surface vertex 25 26 28 27

Creation of Surface 19 (Surface 19) Successful.
This is sheet body 4 (Body 4)
Finished Command: create surface vertex 25 26 28 27

Trelis>
Trelis>section volume 3 with surface 19 keep normal
Created volume(s): 5
SECTION successfully completed
Created volume 5
Finished Command: section volume 3 with surface 19 keep normal

Trelis>section volume 3 with surface 19 reverse
Preserving undo information...done
Updated volume(s): 3
SECTION successfully completed
Created volume 3
Finished Command: section volume 3 with surface 19 reverse

Trelis>
Trelis>delete volume 2 4
Preserving undo information...done
Deleted volume 2
Deleted volume 4
Finished Command: delete volume 2 4

Trelis>
Trelis>merge all

...Merging all features in the model

...Merging all Surfaces in the model
Consolidated 2 pairs of surfaces

...Merging all Curves in the model
Consolidated 0 pair of curves

...Merging all Vertices in the model
Consolidated 0 pairs of vertices
All detected matches successfully merged
Finished Command: merge all

Trelis>imprint all
Preserving undo information...done
Group imprint finished.
IMPRINT completed.
Finished Command: imprint all

Trelis>
Trelis># Meshing the volumes
Trelis>## middle volume
Trelis>#cubit.cmd('volume 3 size 3589.2')
Trelis>volume 3 size 4500.
Finished Command: volume 3 size 4500

Trelis>mesh volume 3
Volume 3 (Volume 3) meshing scheme automatically set to submap.
Matching intervals successful.
Meshing Volume 3 (Volume 3)
Generated 900 faces for Surface 20 (Surface 20).
Generated 150 faces for Surface 27 (Surface 27).
Generated 150 faces for Surface 28 (Surface 28).
Generated 900 faces for Surface 8 (Surface 8).
Generated 150 faces for Surface 29 (Surface 29).
Generated 150 faces for Surface 30 (Surface 30).
Generated 4500 hexes for Volume 3 (Volume 3).
Volume 3 (Volume 3) meshing completed using scheme: submap

Meshing time: 0.160000
Finished Command: mesh volume 3

Trelis>
Trelis># refine boundary surface between top and middle volume
Trelis># this will create a tripling layer from the bottom to the top in the middle volume
Trelis>refine surface 8 numsplit 1 bias 1.0 depth 1
Finished Command: refine surface 8 numsplit 1 bias 1 depth 1

Trelis>
Trelis>#cubit.cmd('pause')
Trelis>
Trelis>## top volume
Trelis>#cubit.cmd('volume 1 size 1196.4')
Trelis>volume 1 size 1000.0
Finished Command: volume 1 size 1000

Trelis>mesh volume 1
Volume 1 (Volume 1) meshing scheme automatically set to submap.
Matching intervals successful.
Meshing Volume 1 (Volume 1)
Generated 270 faces for Surface 15 (Surface 15).
Generated 270 faces for Surface 16 (Surface 16).
Generated 8100 faces for Surface 1 (Surface 1).
Generated 270 faces for Surface 17 (Surface 17).
Generated 270 faces for Surface 18 (Surface 18).
Generated 24300 hexes for Volume 1 (Volume 1).
Volume 1 (Volume 1) meshing completed using scheme: submap

Meshing time: 0.360000
Finished Command: mesh volume 1

Trelis>
Trelis>#cubit.cmd('pause')
Trelis>
Trelis>## bottom volume
Trelis>#cubit.cmd('volume 5 size 4785.71')
Trelis>volume 5 size 4500.
Finished Command: volume 5 size 4500

Trelis>mesh volume 5
Volume 5 (Volume 5) meshing scheme automatically set to submap.
Matching intervals successful.
Meshing Volume 5 (Volume 5)
Generated 240 faces for Surface 21 (Surface 21).
Generated 240 faces for Surface 22 (Surface 22).
Generated 240 faces for Surface 23 (Surface 23).
Generated 240 faces for Surface 24 (Surface 24).
Generated 900 faces for Surface 25 (Surface 25).
Generated 7200 hexes for Volume 5 (Volume 5).
Volume 5 (Volume 5) meshing completed using scheme: submap

Meshing time: 0.150000
Finished Command: mesh volume 5

Trelis>
Trelis># draw/update mesh lines for visualization
Trelis># this will draw also the tripling layer mesh lines
Trelis>draw volume all
Trelis>
Trelis>#### End of meshing
Trelis>
Trelis>###### This is boundary_definition.py of GEOCUBIT
Trelis>#..... which extracts the bounding faces and defines them into blocks
Trelis>
Trelis>
proc  0  is has absorbing boundary xmin
proc  0  is has absorbing boundary ymin
proc  0  is has absorbing boundary xmax
proc  0  is has absorbing boundary ymax
block 4 hex in vol 1 except hex in vol [3, 5]
WARNING: No entity with ID 4 was found
Finished Command: block 4 hex in volume 1 except hex in volume 3 5

Finished Command: block 4 name "vol1"

block 5 hex in vol 3 except hex in vol [1, 5]
WARNING: No entity with ID 5 was found
Finished Command: block 5 hex in volume 3 except hex in volume 1 5

Finished Command: block 5 name "vol3"

block 6 hex in vol 5 except hex in vol [1, 3]
WARNING: No entity with ID 6 was found
Finished Command: block 6 hex in volume 5 except hex in volume 1 3

Finished Command: block 6 name "vol5"

Trelis>
Trelis>#### Define material properties for the 3 volumes ################
Trelis>#### DEFINE MATERIAL PROPERTIES #######################
Trelis>block 1 name "elastic 1"
WARNING: No entity with ID 1 was found
ERROR: /home/chzhang/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (98)
       No entity with ID 1 was found
ERROR: /home/chzhang/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (98)
       No entities specified.
Trelis>block 1 attribute count 6
WARNING: No entity with ID 1 was found
ERROR: /home/chzhang/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (99)
       No entity with ID 1 was found
ERROR: /home/chzhang/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (99)
       No entities specified.
Trelis>block 1 attribute index 1 1 
WARNING: No entity with ID 1 was found
ERROR: /home/chzhang/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (100)
       No entity with ID 1 was found
ERROR: /home/chzhang/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (100)
       No entities specified.
Trelis>block 1 attribute index 2 2800
WARNING: No entity with ID 1 was found
ERROR: /home/chzhang/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (101)
       No entity with ID 1 was found
ERROR: /home/chzhang/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (101)
       No entities specified.
Trelis>block 1 attribute index 3 1500
WARNING: No entity with ID 1 was found
ERROR: /home/chzhang/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (102)
       No entity with ID 1 was found
ERROR: /home/chzhang/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (102)
       No entities specified.
Trelis>block 1 attribute index 4 2300
WARNING: No entity with ID 1 was found
ERROR: /home/chzhang/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (103)
       No entity with ID 1 was found
ERROR: /home/chzhang/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (103)
       No entities specified.
Trelis>block 1 attribute index 5 9000.0
WARNING: No entity with ID 1 was found
ERROR: /home/chzhang/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (104)
       No entity with ID 1 was found
ERROR: /home/chzhang/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (104)
       No entities specified.
Trelis>block 1 attribute index 6 0
WARNING: No entity with ID 1 was found
ERROR: /home/chzhang/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (105)
       No entity with ID 1 was found
ERROR: /home/chzhang/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (105)
       No entities specified.
Trelis>
Trelis>block 2 name "elastic 2"
WARNING: No entity with ID 2 was found
ERROR: /home/chzhang/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (107)
       No entity with ID 2 was found
ERROR: /home/chzhang/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (107)
       No entities specified.
Trelis>block 2 attribute count 6
WARNING: No entity with ID 2 was found
ERROR: /home/chzhang/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (108)
       No entity with ID 2 was found
ERROR: /home/chzhang/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (108)
       No entities specified.
Trelis>block 2 attribute index 1 2 
WARNING: No entity with ID 2 was found
ERROR: /home/chzhang/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (109)
       No entity with ID 2 was found
ERROR: /home/chzhang/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (109)
       No entities specified.
Trelis>block 2 attribute index 2 7500
WARNING: No entity with ID 2 was found
ERROR: /home/chzhang/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (110)
       No entity with ID 2 was found
ERROR: /home/chzhang/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (110)
       No entities specified.
Trelis>block 2 attribute index 3 4300
WARNING: No entity with ID 2 was found
ERROR: /home/chzhang/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (111)
       No entity with ID 2 was found
ERROR: /home/chzhang/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (111)
       No entities specified.
Trelis>block 2 attribute index 4 3200
WARNING: No entity with ID 2 was found
ERROR: /home/chzhang/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (112)
       No entity with ID 2 was found
ERROR: /home/chzhang/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (112)
       No entities specified.
Trelis>block 2 attribute index 5 9000.0
WARNING: No entity with ID 2 was found
ERROR: /home/chzhang/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (113)
       No entity with ID 2 was found
ERROR: /home/chzhang/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (113)
       No entities specified.
Trelis>block 2 attribute index 6 0
WARNING: No entity with ID 2 was found
ERROR: /home/chzhang/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (114)
       No entity with ID 2 was found
ERROR: /home/chzhang/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (114)
       No entities specified.
Trelis>
Trelis>block 3 name "elastic 3"
WARNING: No entity with ID 3 was found
ERROR: /home/chzhang/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (116)
       No entity with ID 3 was found
ERROR: /home/chzhang/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (116)
       No entities specified.
Trelis>block 3 attribute count 6
WARNING: No entity with ID 3 was found
ERROR: /home/chzhang/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (117)
       No entity with ID 3 was found
ERROR: /home/chzhang/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (117)
       No entities specified.
Trelis>block 3 attribute index 1 3 
WARNING: No entity with ID 3 was found
ERROR: /home/chzhang/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (118)
       No entity with ID 3 was found
ERROR: /home/chzhang/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (118)
       No entities specified.
Trelis>block 3 attribute index 2 7500
WARNING: No entity with ID 3 was found
ERROR: /home/chzhang/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (119)
       No entity with ID 3 was found
ERROR: /home/chzhang/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (119)
       No entities specified.
Trelis>block 3 attribute index 3 4300
WARNING: No entity with ID 3 was found
ERROR: /home/chzhang/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (120)
       No entity with ID 3 was found
ERROR: /home/chzhang/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (120)
       No entities specified.
Trelis>block 3 attribute index 4 3200
WARNING: No entity with ID 3 was found
ERROR: /home/chzhang/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (121)
       No entity with ID 3 was found
ERROR: /home/chzhang/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (121)
       No entities specified.
Trelis>block 3 attribute index 5 9000.0
WARNING: No entity with ID 3 was found
ERROR: /home/chzhang/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (122)
       No entity with ID 3 was found
ERROR: /home/chzhang/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (122)
       No entities specified.
Trelis>block 3 attribute index 6 0
WARNING: No entity with ID 3 was found
ERROR: /home/chzhang/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (123)
       No entity with ID 3 was found
ERROR: /home/chzhang/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (123)
       No entities specified.
Trelis>
Trelis>export mesh "top.e" dimension 3 overwrite

Using ExodusII API version 4.98 and DB version 4.98 to export "top.e".

Executive Exodus summary:
  Number of dimensions     = 3
  Number of element blocks = 3
  Number of sidesets       = 0
  Number of nodesets       = 0
  Number of bc sets        = 1
  Number of elements       = 70200
  Number of nodes          = 76819

Finished writing top.e
Finished Command: export mesh "top.e" dimension 3 overwrite

Trelis>save as "meshing.cub" overwrite

Exported:   3 Volumes

Successfully saved CUBIT file 'meshing.cub'
Finished Command: save as "meshing.cub" overwrite

Trelis>
Trelis>#### Export to SPECFEM3D format using cubit2specfem3d.py of GEOCUBIT
Trelis>
Trelis>
Trelis>
HEX Blocks:
block  4 material flag  4
block  5 material flag  5
block  6 material flag  6
Absorbing Boundary Conditions:
Topography (free surface)
None
Free surface
None
Preserving undo information...done
Finished Command: compress all

Turning informational messages off.
Writing MESH/mesh_file.....
 total number of elements: 70200
block  4  hexes  24300
block  5  hexes  38700
block  6  hexes  7200
Writing MESH/materials_file.....
block  4 flag  4
block  5 flag  5
block  6 flag  6
Writing MESH/nodes_coords_file.....
  number of nodes: 76819
Writing MESH/free_or_absorbing_surface_file_zmax.....
Echoing has been turned ON
Finished Command: set echo on

Turning informational messages off.
Echoing has been turned ON
Finished Command: set echo on

Writing MESH/nummaterial_velocity_file.....
Turning informational messages on.
Finished Command: set info on

Echoing has been turned ON
Finished Command: set echo on

END SPECFEM3D exporting process......
Trelis>
Trelis># all files needed by SCOTCH are now in directory MESH
Trelis>
Trelis>

**Comment by komatits** [comment]
Hi @specfem3d-zhang-ksu and @casarotti ,

Any update on this bug? Can I close the issue on GitHub?

Thanks,
Dimitri.

**Comment by casarotti** [comment]
this should be ok now....
maybe not on the master

**Comment by komatits** [comment]
Thanks! let me close it then.

Dimitri.

On 02/09/2015 12:25 PM, emanuele casarotti wrote:
> this should be ok now....
> maybe not on the master
>
> On Mon Feb 09 2015 at 11:31:59 Dimitri Komatitsch <notifications@github.com>
> wrote:
>
>  > Hi @specfem3d-zhang-ksu <https://github.com/specfem3d-zhang-ksu> and
>  > @casarotti <https://github.com/casarotti> ,
>  >
>  > Any update on this bug? Can I close the issue on GitHub?
>  >
>  > Thanks,
>  > Dimitri.
>  >
>  > —
>  > Reply to this email directly or view it on GitHub
>  >
> <https://github.com/geodynamics/specfem3d/issues/330#issuecomment-73487234>
>  > .
>  >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/issues/330#issuecomment-73493813>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by specfem3d-zhang-ksu** [comment]
Not sure because I don't have an active trelis anymore.
