### ISSUE TITLE
consider supporting Hex27 element in dynamic fault solver

### ISSUE THREAD

**Issue by kbai** [geodynamics/specfem3d#343]
When dealing with curved surfaces, Hex27 should take advantage over Hex8 elements and latest CUBIT seems to support Hex27 generation . I remember previously people reporting cubit's inability to generate real Hex27 elements(issue #48 ) that follows the surface geometry but now it seems that the problem no longer exist. If that is true, we should consider supporting Hex27 element in dynamic fault solver.

**Comment by komatits** [comment]
Yes, CUBIT / TRELIS now has support for HEX27.

**Comment by komatits** [comment]
Done by @kbai .
