### ISSUE TITLE
source encoding better implemented outside of SPECFEM?

### ISSUE THREAD

**Issue by rmodrak** [geodynamics/specfem3d#418]
- Considering that source encoding can be easily implemented through a script outside of SPECFEM, does it make sense to include it as a feature of SPECFEM? 

- There are many different types of source encoding, some quite involved.  Although the current implementation is quite simple, if left in the solver, it could grow over time.

- Without an extensions mechanism, accumulation of marginal features adds to a package's complexity, making it more difficult to read and maintain.  It may be worthwhile to consider simple workarounds to reduce feature overload.  

- The scripting approach, which involves using a sed command to change values in the CMTSOULTION file, is one Yanhua and myself have taken.  It works well and is quite flexible.

- Source encoding techniques were developed originally by industry and are protected by numerous patents.  I don't believe this affects academic users, but it is something for commercial users to be aware of.

**Comment by komatits** [comment]
Hi,

We can leave it, it does not hurt (there are many other optional 
features in the Par_file). It could be quite useful (the scripts you 
mention are currently not in the package I think, and thus unusable). 
Other option: committing these scripts + a HOWTO.

Best wishes,
Dimitri.

On 02/17/2015 01:09 AM, rmodrak wrote:
>   *
>
>     Considering that source encoding can be easily implemented through a
>     script outside of SPECFEM, does it make sense to include it as a
>     feature of SPECFEM?
>
>   *
>
>     There are many different types of source encoding, some quite
>     involved. Although the current implementation is quite simple, if
>     left in the solver, it could grow over time.
>
>   *
>
>     Without an extensions mechanism, accumulation of marginal features
>     adds to a package's complexity, making it more difficult to read and
>     maintain. It may be worthwhile to consider simple workarounds to
>     reduce feature overload.
>
>   *
>
>     The scripting approach, which involves using a sed command to change
>     values in the CMTSOULTION file, is one Yanhua and myself have taken.
>     It works well and is quite flexible.
>
>   *
>
>     Source encoding techniques were developed originally by industry and
>     are protected by numerous patents. I don't believe this affects
>     academic users, but it is something for commercial users to be aware of.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/issues/418>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr
