### ISSUE TITLE
distinguish between postprocessing and optimization routines through separate directories?

### ISSUE THREAD

**Issue by rmodrak** [geodynamics/specfem3d#420]
- For both conceptual and practical purposes, there is a useful distinction between postprocessing routines, which yield the gradient direction, and optimization routines, which yield the model update direction.

- It is often helpful to reduce the extent to which model parameters are hardwired into the code.  Currently, it would be quite hard to removable hardwired parameters from all the optimization routines.  It would be fairly easy, however, to remove hardwired parameters from the postprocessing routines.  In fact, Daniel has already done this for smooth_sem, and I am about to submit a pull request to remove hardwired parameters from sum_kernels.

- Incidentally, it turns out that many users need the included smoothing and summing routines, but not the optimization routines.

For all the above reasons, it could be helpful to do the following:

split src/tomography into two directories: src/optimize and src/postprocess 

If the main developers are in favor of this change, I could go ahead and submit a pull request.

**Comment by rmodrak** [comment]
UPDATE:  There are a number of new or refactored postprocessing utilities that follow Daniel's naming convention and avoid hardwired paths.

In specfem3d: xclip_sem, xcombine_sem, xsmooth_sem

In specfem3d_globe: xaddtion_sem, xcombine_sem, xdifference_sem, xsmooth_sem

These routines differ from others in src/tomography in that they share a consistent interface and get names of directories and of elastic moduli from the command line, rather than from hardwired entries.  

I still think it makes sense to move these routines to a different subdirectory.  If doing so would cause any disruption, though, they could stay where they currently are.  If anyone feels strongly, please weigh in, otherwise I'll move them.

(Note: I have been and will continue to work on making the specfem3d and specfem3d_globe utilities more consistent.)

**Comment by komatits** [comment]
Great, this is excellent news, and very useful
(as long as we document it somewhere so that people know how to use the 
new routines).

Thanks!
Dimitri.

On 02/22/2015 04:55 PM, rmodrak wrote:
> UPDATE: There are a number of new or refactored postprocessing utilities
> that follow Daniel's naming convention and avoid hardwired paths.
>
> In specfem3d: xclip_sem, xcombine_sem, xsmooth_sem
>
> In specfem3d_globe: xaddtion_sem, xcombine_sem, xdifference_sem, xsmooth_sem
>
> These routines differ from others in src/tomography in that they share a
> consistent interface and get names of directories and of elastic moduli
> from the command line, rather than from hardwired entries.
>
> I still think it makes sense to move these routines to a different
> subdirectory. If doing so would cause any disruption, though, they could
> stay where they currently are. If anyone feels strongly, please weigh
> in, otherwise I'll move them.
>
> (Note: I have been and will continue to work on making the specfem3d and
> specfem3d_globe utilities more consistent.)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/issues/420#issuecomment-75441728>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by rmodrak** [comment]
Just to clarify, four out of six of the routines in my last comment above were created by Daniel, two were created by me.

**Comment by rmodrak** [comment]
As for documentation, unfortunately, it seems like none of the postprocessing or nonlinear optimization routines have ever been mentioned in the user manual.  There are however, detailed usage notes for each of the above postprocessing routines within the source code.  I tried to make these notes more thorough and consistent from one file to another.

**Comment by rmodrak** [comment]
FINAL UPDATE: To distinguish between postprocessing and optimization routines, a new subdirectory, `src/postprocess`, has been created.

I hope others will find this more clear because, instead of having a mix of conventions, now all the routines within `src/tomography` follow one consistent convention, and all the routines within `src/postprocess` follow another.

**Comment by rmodrak** [comment]
I think this issue has been addressed.  If there are no further comments, I'll go ahead and close it shortly.
