### ISSUE TITLE
replace hardwired material parameter thresholds in model_update.f90 with a new clip_sem.f90 utility

### ISSUE THREAD

**Issue by rmodrak** [geodynamics/specfem3d#424]
Currently, model_update.f90 contains hardwired vp,vs, and rho thresholds based on a particular geologic region (Southern California).  A more useful and flexible approach is to provide a clip_sem utility that obtains threshold vales from the command line.  The utility could be modeled closely on Daniel’s existing smooth_sem program.

If there are no objections, I will go ahead and create such a utility in a new src/postprocess directory.

**Comment by casarotti** [comment]
Hi rmodrak,
I think that the hardwired value are not considered in the script... I
suppose we can remove directly....
Emanuele

**Comment by rmodrak** [comment]
Hi Emmanuele,

It looks like the hardwired thresholds in lines of 57-64 of model_update
are applied to vp,vs,rho arrays. Then, in lines 344-358, the thresholded
vp,vs,rho arrays are used to compute the updated model.  It seems like if
the hardwired thresholds were removed, it would produce different slightly
results from the program.  Is this right?  Please let me know if I am
missing anything.

Thanks,
Ryan

**Comment by komatits** [comment]
Hi all,

Let us remove all hardwired values and let us clarify / simplify this.

Thanks,
Dimitri.

On 02/19/2015 02:59 PM, rmodrak wrote:
> Hi Emmanuele,
>
> It looks like the hardwired thresholds in lines of 57-64 of model_update
> are applied to vp,vs,rho arrays. Then, in lines 344-358, the thresholded
> vp,vs,rho arrays are used to compute the updated model. It seems like if
> the hardwired thresholds were removed, it would produce different slightly
> results from the program. Is this right? Please let me know if I am
> missing anything.
>
> Thanks,
> Ryan
>
> On Thu, Feb 19, 2015 at 4:17 AM, emanuele casarotti <
> notifications@github.com> wrote:
>
>  > Hi rmodrak,
>  > I think that the hardwired value are not considered in the script... I
>  > suppose we can remove directly....
>  > Emanuele
>  >
>  > On Thu Feb 19 2015 at 05:01:41 rmodrak <notifications@github.com> wrote:
>  >
>  > > Currently, model_update.f90 contains hardwired vp,vs, and rho
> thresholds
>  > > based on a particular geologic region (Southern California). A more
>  > useful
>  > > and flexible approach is to provide a clip_sem utility that obtains
>  > > threshold vales from the command line. The utility could be modeled
>  > closely
>  > > on Daniel’s existing smooth_sem program.
>  > >
>  > > If there are no objections, I will go ahead and create such a
> utility in
>  > a
>  > > new src/postprocess directory.
>  > >
>  > > —
>  > > Reply to this email directly or view it on GitHub
>  > > <https://github.com/geodynamics/specfem3d/issues/424>.
>  > >
>  >
>  > —
>  > Reply to this email directly or view it on GitHub
>  >
> <https://github.com/geodynamics/specfem3d/issues/424#issuecomment-75019435>
>  > .
>  >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/issues/424#issuecomment-75055673>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by rmodrak** [comment]
I've submitted a pull request for a new utility, xclip_sem.

**Comment by rmodrak** [comment]
Hi Dimitri,  To create a place to respond to your comment "Let us remove all hardwired values", I am opening a new issue about refactoring nonlinear optimization routines.   (The issue we are on currently seems a bit narrow to hold the kind of discussion that would be required.)

**Comment by komatits** [comment]
Done by Ryan @rmodrak .
