### ISSUE TITLE
what is the right place to specify tomography paths?

### ISSUE THREAD

**Issue by rmodrak** [geodynamics/specfem3d#425]
Paths used by the tomography routines are specified in at least three places

- setup/constants_tomography.h
- src/tomography/tomography_par.f90
- hardwired into the code

Is there any reason not to have a single location?

**Comment by komatits** [comment]
Hi,

You are right, let us keep a single one
(probably setup/constants_tomography.h then)

Thanks,
Dimitri.

On 02/19/2015 05:02 AM, rmodrak wrote:
> Paths used by the tomography routines are specified in at least three places
>
>   * setup/constants_tomography.h
>   * src/tomography/tomography_par.f90
>   * hardwired into the code
>
> Is there any reason not to have a single location?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/issues/425>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by komatits** [comment]
PS: Let us mention that in the SPECFEM users manual as well (i.e. tell 
users where the constants are)

Dimitri

On 02/21/2015 04:44 PM, Dimitri Komatitsch wrote:
>
> Hi,
>
> You are right, let us keep a single one
> (probably setup/constants_tomography.h then)
>
> Thanks,
> Dimitri.
>
> On 02/19/2015 05:02 AM, rmodrak wrote:
>> Paths used by the tomography routines are specified in at least three
>> places
>>
>>   * setup/constants_tomography.h
>>   * src/tomography/tomography_par.f90
>>   * hardwired into the code
>>
>> Is there any reason not to have a single location?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/geodynamics/specfem3d/issues/425>.
>>
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by rmodrak** [comment]
UPDATE:  

Tomography paths have been moved from tomography_par to tomography_constants.

This is a simple change, but still it would be good to test the src/tomography routines.  Once Issue #396 is resolved, we could go ahead and do this.

If it's alright, I'll go ahead and close this issue.
