### ISSUE TITLE
USE_SEPARATE_CG_STEPLENGTHS deprecated

### ISSUE THREAD

**Issue by rmodrak** [geodynamics/specfem3d#426]
Has anyone encountered a situation for which this feature is useful?  I’m not sure it’s a good idea to include it.

In most cases, it is better to invert multiple parameters simultaneously rather than one at a time.  For example, it is better to invert source and structure through a simultaneous inversion rather than through alternating decoupled iterations.

Put another way, treating each parameter one at a time is a kind of coordinate descent approach.  There is some applied math literature showing that these methods tend to perform badly.

**Comment by komatits** [comment]
Indeed it could probably be removed. Vadim and Yi, could you confirm 
that you never use it and that Ryan can remove it?

Thanks,
Dimitri.

On 02/19/2015 05:04 AM, rmodrak wrote:
> In most cases, is better to invert multiple parameters simultaneously
> rather than one at a time. For example, it is better to invert source
> and structure through a simultaneous inversion rather than through
> alternating decoupled iterations. The underlying idea--to treat each
> parameter separately, one at a time--is also the basis for coordinate
> descent methods, which tend to perform quite poorly.
>
> Has anyone encountered a situation for which this feature is useful? I’m
> not sure it’s a good idea to include it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/issues/426>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by rmodrak** [comment]
A comment about this feature has been added above the parameter definition in constants_tomography.  If it's alright, I'll go ahead and close this issue.
