### ISSUE TITLE
minor terminology errors in src/tomography

### ISSUE THREAD

**Issue by rmodrak** [geodynamics/specfem3d#427]
* rename write_gradients -> write_gradient

Even though there may be multiple elastic parameters, there is only one gradient.  It is not correct to speak of multiple gradients.

There may be some underlying confusion here about the optimization procedure (see also the concerns about USE_SEPARATE_CG_STEPLENGTHS ).

In addition to these proposed filename changes, there are a number of minor changes to the source code comments that I could go ahead and make.

* rename get_gradient_cg -> get cg_direction
* rename get_gradient_steepest -> get_sd_direction

This is just a question of terminology. It is correct to speak of the conjugate gradient or steepest descent direction (not the conjugate gradient or steepest descent gradient).

**Comment by komatits** [comment]
Thanks! I do not see any corresponding pull request though. Did you 
create one?

Dimitri.

On 02/19/2015 05:10 AM, rmodrak wrote:
>   * rename write_gradients -> write_gradient
>
> Even though there may be multiple elastic parameters, there is only one
> gradient. It is not correct to speak of multiple gradients.
>
> There may be some underlying confusion here about the optimization
> procedure (see also the concerns about USE_SEPARATE_CG_STEPLENGTHS ).
>
> In addition to these proposed filename changes, there are a number of
> minor changes to the source code comments that I could go ahead and make.
>
>   * rename get_gradient_cg -> get cg_direction
>   * rename get_gradient_steepest -> get_sd_direction
>
> This is just a question of terminology. It is correct to speak of the
> conjugate gradient or steepest descent direction (not the conjugate
> gradient or steepest descent gradient).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/issues/427>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by rmodrak** [comment]
I've submitted the pull request.

**Comment by komatits** [comment]
Hi Ryan,

Regarding "gradients" versus "gradient" in general I think this refers 
to the fact that one can choose between different misfit functions; as 
you say there is only one gradient once a given misfit function is 
chosen, but for that misfit different choices can be made.

However as you say in the code it probably makes more sense to use 
"gradient".

Best wishes,
Dimitri.

On 02/19/2015 05:10 AM, rmodrak wrote:
>   * rename write_gradients -> write_gradient
>
> Even though there may be multiple elastic parameters, there is only one
> gradient. It is not correct to speak of multiple gradients.
>
> There may be some underlying confusion here about the optimization
> procedure (see also the concerns about USE_SEPARATE_CG_STEPLENGTHS ).
>
> In addition to these proposed filename changes, there are a number of
> minor changes to the source code comments that I could go ahead and make.
>
>   * rename get_gradient_cg -> get cg_direction
>   * rename get_gradient_steepest -> get_sd_direction
>
> This is just a question of terminology. It is correct to speak of the
> conjugate gradient or steepest descent direction (not the conjugate
> gradient or steepest descent gradient).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/issues/427>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by rmodrak** [comment]
Hi Dimitri,  That's a good point, I didn't think of that.  I believe though at least one contributor used 'gradients' in the sense of one gradients for each elastic modulus--certain comments in the code made that clear.  In addition to changing the filenames, I revised these comments.

**Comment by komatits** [comment]
Done by Ryan @rmodrak .
