### ISSUE TITLE
Nightly build fails because examples don't generate the same seismograms

### ISSUE THREAD

**Issue by luet** [geodynamics/specfem3d#460]
In the EXAMPLE homogeneous_halfspace_HEX8_elastic_absorbing_Stacey_5sides, by default OUTPUT_FILES with extension sema, semd and semv were generated. Now only semd files are generated.
This started with @komatits commit fa6b2aa4ce
If this is what we want then I'll change the reference seismograms to only include the semd files. Just let me know.
Best,
David

**Comment by komatits** [comment]
Hi David,

I think checking the displacement seismograms is sufficient.

Otherwise in DATA/Par_file of that example just change

SAVE_SEISMOGRAMS_VELOCITY       = .false.
SAVE_SEISMOGRAMS_ACCELERATION   = .false.

to .true.

Thanks,
Dimitri.

On 03/16/2015 05:44 PM, David Luet wrote:
> In the EXAMPLE
> homogeneous_halfspace_HEX8_elastic_absorbing_Stacey_5sides, by default
> OUTPUT_FILES with extension sema, semd and semv were generated. Now only
> semd files are generated.
> This started with @komatits <https://github.com/komatits> commit fa6b2aa
> <https://github.com/geodynamics/specfem3d/commit/fa6b2aa4ce2e3c12767e797e17a05b2f5f3ce0af>
> If this is what we want then I'll change the reference seismograms to
> only include the semd files. Just let me know.
> Best,
> David
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/issues/460>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by luet** [comment]
I'll keep only the displacement. I want buildbot to run the EXAMPLES the
way they are in the repo.
Thanks,
David

On Mon, Mar 16, 2015 at 12:54 PM, Dimitri Komatitsch <
notifications@github.com> wrote:

>
> Hi David,
>
> I think checking the displacement seismograms is sufficient.
>
> Otherwise in DATA/Par_file of that example just change
>
> SAVE_SEISMOGRAMS_VELOCITY = .false.
> SAVE_SEISMOGRAMS_ACCELERATION = .false.
>
> to .true.
>
> Thanks,
> Dimitri.
>
> On 03/16/2015 05:44 PM, David Luet wrote:
> > In the EXAMPLE
> > homogeneous_halfspace_HEX8_elastic_absorbing_Stacey_5sides, by default
> > OUTPUT_FILES with extension sema, semd and semv were generated. Now only
> > semd files are generated.
> > This started with @komatits <https://github.com/komatits> commit fa6b2aa
> > <
> https://github.com/geodynamics/specfem3d/commit/fa6b2aa4ce2e3c12767e797e17a05b2f5f3ce0af
> >
> > If this is what we want then I'll change the reference seismograms to
> > only include the semd files. Just let me know.
> > Best,
> > David
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/geodynamics/specfem3d/issues/460>.
> >
>
> --
> Dimitri Komatitsch
> CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
> UPR 7051, Marseille, France http://komatitsch.free.fr
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/issues/460#issuecomment-81801942>
> .
>



-- 
David Luet
Linux Administrator/Software & Programming Analyst
Department of Geosciences & PICSciE
Princeton University
