### ISSUE TITLE
Compilation issue on Cygwin

### ISSUE THREAD

**Issue by wanglongqi** [geodynamics/specfem3d#466]
I tried to compile specfem3d on windows, following error pops out:

	gcc -O3 -DCOMMON_FILE_COMPRESS_GZ -DCOMMON_PTHREAD -DCOMMON_RANDOM_FIXED_SEED -DSCOTCH_RENAME -DSCOTCH_RENAME_PARSER -DSCOTCH_PTHREAD -Drestrict=__restrict  -c common.c -DSCOTCH_COMMON_RENAME -o common.o
	common.c: In function '_SCOTCHclockGet':
	common.c:116:23: error: storage size of 'tv' isn't known
	   struct timeval      tv;
	                       ^
	Makefile:395: recipe for target 'common.o' failed
	make[4]: *** [common.o] Error 1

The same compilation environment can compile specfem2d successfully, any suggestion on the problem? Thank you!

**Comment by komatits** [comment]
Dear Longqi,

This error message comes from the SCOTCH library that is called by 
SPECFEM, not from the source code of SPECFEM itself; thus let me cc 
François Pellegrini, the main author of SCOTCH.

François, do you know if SCOTCH compiles fine in Windows systems with 
Cygwin?

Thanks,
Dimitri.

On 03/22/2015 02:39 PM, WANG Longqi wrote:
> I tried to compile specfem3d on windows, following error pops out:
>
> |gcc -O3 -DCOMMON_FILE_COMPRESS_GZ -DCOMMON_PTHREAD -DCOMMON_RANDOM_FIXED_SEED -DSCOTCH_RENAME -DSCOTCH_RENAME_PARSER -DSCOTCH_PTHREAD -Drestrict=__restrict  -c common.c -DSCOTCH_COMMON_RENAME -o common.o
> common.c: In function '_SCOTCHclockGet':
> common.c:116:23: error: storage size of 'tv' isn't known
>     struct timeval      tv;
>                         ^
> Makefile:395: recipe for target 'common.o' failed
> make[4]: *** [common.o] Error 1
> |
>
> The same compilation environment can compile specfem2d successfully, any
> suggestion on the problem? Thank you!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/issues/466>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by wanglongqi** [comment]
Dear Dimitri,

Yes, the error is coming from SCOTCH. I do not think SCOTCH can compile correctly on Windows, but it seems SPECFEM2D also uses SCOTCH, which can be compiled correctly. 

All the other components can be compiled correctly with Cygwin.

Thanks,
Longqi

**Comment by wanglongqi** [comment]
The problem is solved by commenting following codes in `common.c` and add a dummy time as stated in the code before.

	#else /* defined (_POSIX_TIMERS) && (_POSIX_TIMERS >= 200112L) */
	/*  struct timeval      tv;

	  gettimeofday (&tv, NULL);

	 return ((double) tv.tv_sec + (double) tv.tv_usec * 1.0e-6L);*/
	 return (1.0e-6L);

**Comment by komatits** [comment]
Thanks! Very useful. I have cut and pasted your fix in the official 
version of SPECFEM2D and of SPECFEM3D.

Dimitri.

On 04/16/2015 02:06 PM, WANG Longqi wrote:
> The problem is solved by commenting following codes in |common.c| and
> add a dummy time as stated in the code before.
>
> |#else /* defined (_POSIX_TIMERS) && (_POSIX_TIMERS >= 200112L) */
> /*  struct timeval      tv;
>
>    gettimeofday (&tv, NULL);
>
>   return ((double) tv.tv_sec + (double) tv.tv_usec * 1.0e-6L);*/
>   return (1.0e-6L);
> |
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/issues/466#issuecomment-93718013>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by FrPellegrini** [comment]
Hello all,
Sorry for the inconvenience. Date/time management is a pain in the *** as far as portability is concerned.  :-(
Indeed, commenting out the whole offending code is a solution, but it won't provide you with meaningful timing results. In the 6.0.x branch of Scotch, there is a whole routine that is supposed to run with Windows, if you compile it with the "-DCOMMON_WINDOWS" flag set. The code is in lines 80-98 of src/libscotch/common.c .
Hope this helps...
f.p.

**Comment by komatits** [comment]
Dear François,

Thanks!

Dimitri.

On 04/27/2015 07:49 PM, FrPellegrini wrote:
> Hello all,
> Sorry for the inconvenience. Date/time management is a pain in the ***
> as far as portability is concerned. :-(
> Indeed, commenting out the whole offending code is a solution, but it
> won't provide you with meaningful timing results. In the 6.0.x branch of
> Scotch, there is a whole routine that is supposed to run with Windows,
> if you compile it with the "-DCOMMON_WINDOWS" flag set. The code is in
> lines 80-98 of src/libscotch/common.c .
> Hope this helps...
> f.p.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/issues/466#issuecomment-96755984>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr
