### ISSUE TITLE
geocubit wouldn't work on trelis 15.1.3: NameError: name 'boundary_definition' is not defined

### ISSUE THREAD

**Issue by specfem3d-zhang-ksu** [geodynamics/specfem3d#488]
Trelis>#!/usr/bin/env python
Trelis>
Trelis>###########################################################################
Trelis>#### TNM: This is the mesh generation, adapted from a journal file
Trelis>####      specific to the settings of Komatitsch and Tromp 1999, Fig.8
Trelis>####      Aug 2009
Trelis>###########################################################################
Trelis>
Trelis>
Trelis>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named boundary_definition
Trelis>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named cubit2specfem3d
Trelis>
Trelis>
Trelis>
Trelis>
Trelis>reset
Journaled Command: reset

Trelis>brick x 134000 y 134000 z 60000
Successfully created brick volume 1 
Journaled Command: brick x 134000 y 134000 z 60000

Trelis>
Trelis># This seems to conflict with boundary_definition.py
Trelis># ....which leaves the model space at e.g. x=[-67,67] km
Trelis>volume 1 move x 67000 y 67000 z -30000
Journaled Command: volume 1 move x 67000 y 67000 z -30000

Trelis>
Trelis># create vertices for discontinuity
Trelis>
Trelis>split curve 9  distance '+str(distance))
Preserving undo information...done
Updated volume(s): 1
Journaled Command: split curve 9 distance 3000

Trelis>split curve 10  distance '+str(distance))
Preserving undo information...done
Updated volume(s): 1
Journaled Command: split curve 10 distance 3000

Trelis>split curve 11  distance '+str(distance))
Preserving undo information...done
Updated volume(s): 1
Journaled Command: split curve 11 distance 3000

Trelis>split curve 12  distance '+str(distance))
Preserving undo information...done
Updated volume(s): 1
Journaled Command: split curve 12 distance 3000

Trelis>
Trelis># create surface for interface
Trelis># surface at 3 km depth
Trelis>create surface vertex 9 10 12 11

Creation of Surface 7 (Surface 7) Successful.
This is sheet body 2 (Body 2)
Journaled Command: create surface vertex 9 10 12 11

Trelis>
Trelis>section volume 1 with surface 7 keep normal
Created volume(s): 3
SECTION successfully completed
Created volume 3 
Journaled Command: section volume 1 with surface 7 keep normal

Trelis>section volume 1 with surface 7 reverse
Preserving undo information...done
Updated volume(s): 1
SECTION successfully completed
Created volume 1 
Journaled Command: section volume 1 with surface 7 reverse

Trelis>
Trelis># create vertices for auxiliary interface to allow for refinement
Trelis>#distance = 9000
Trelis># to have a surface at 25050 m depth, such that point force source can be located exactly
Trelis># on a GLL point at that depth as in Komatitsch et al. (1999)
Trelis>
Trelis>split curve 29  distance '+str(distance))
Preserving undo information...done
Updated volume(s): 3
Journaled Command: split curve 29 distance 22050

Trelis>split curve 31  distance '+str(distance))
Preserving undo information...done
Updated volume(s): 3
Journaled Command: split curve 31 distance 22050

Trelis>split curve 32  distance '+str(distance))
Preserving undo information...done
Updated volume(s): 3
Journaled Command: split curve 32 distance 22050

Trelis>split curve 36  distance '+str(distance))
Preserving undo information...done
Updated volume(s): 3
Journaled Command: split curve 36 distance 22050

Trelis>
Trelis>
Trelis># create surface for buffer interface to refine BELOW the discontinuity
Trelis># surface at 3 km depth
Trelis>create surface vertex 25 26 28 27

Creation of Surface 19 (Surface 19) Successful.
This is sheet body 4 (Body 4)
Journaled Command: create surface vertex 25 26 28 27

Trelis>
Trelis>section volume 3 with surface 19 keep normal
Created volume(s): 5
SECTION successfully completed
Created volume 5 
Journaled Command: section volume 3 with surface 19 keep normal

Trelis>section volume 3 with surface 19 reverse
Preserving undo information...done
Updated volume(s): 3
SECTION successfully completed
Created volume 3 
Journaled Command: section volume 3 with surface 19 reverse

Trelis>
Trelis>delete volume 2 4
Preserving undo information...done
Deleted volume 2 
Deleted volume 4 
Journaled Command: delete volume 2 4

Trelis>
Trelis>merge all

...Merging all features in the model

...Merging all Surfaces in the model
Consolidated 2 pairs of surfaces

...Merging all Curves in the model
Consolidated 0 pair of curves 

...Merging all Vertices in the model
Consolidated 0 pairs of vertices
All detected matches successfully merged
Journaled Command: merge all

Trelis>imprint all
Preserving undo information...done
Group imprint finished.
IMPRINT completed.
Journaled Command: imprint all

Trelis>
Trelis># Meshing the volumes
Trelis>## middle volume
Trelis>#cubit.cmd('volume 3 size 3589.2')
Trelis>volume 3 size 4500.
Journaled Command: volume 3 size 4500

Trelis>mesh volume 3
Volume 3 (Volume 3) meshing scheme automatically set to submap.
Matching intervals successful.
Meshing Volume 3 (Volume 3)
Generated 900 faces for Surface 20 (Surface 20).
Generated 150 faces for Surface 27 (Surface 27).
Generated 150 faces for Surface 28 (Surface 28).
Generated 900 faces for Surface 8 (Surface 8).
Generated 150 faces for Surface 29 (Surface 29).
Generated 150 faces for Surface 30 (Surface 30).
Generated 4500 hexes for Volume 3 (Volume 3).
Volume 3 (Volume 3) meshing completed using scheme: submap

Meshing time: 0.060000 
Journaled Command: mesh volume 3

Trelis>
Trelis># refine boundary surface between top and middle volume
Trelis># this will create a tripling layer from the bottom to the top in the middle volume
Trelis>refine surface 8 numsplit 1 bias 1.0 depth 1
Journaled Command: refine surface 8 numsplit 1 bias 1 depth 1

Trelis>
Trelis>#cubit.cmd('pause')
Trelis>
Trelis>## top volume
Trelis>#cubit.cmd('volume 1 size 1196.4')
Trelis>volume 1 size 1000.0
Journaled Command: volume 1 size 1000

Trelis>mesh volume 1
Volume 1 (Volume 1) meshing scheme automatically set to submap.
Matching intervals successful.
Meshing Volume 1 (Volume 1)
Generated 270 faces for Surface 15 (Surface 15).
Generated 270 faces for Surface 16 (Surface 16).
Generated 8100 faces for Surface 1 (Surface 1).
Generated 270 faces for Surface 17 (Surface 17).
Generated 270 faces for Surface 18 (Surface 18).
Generated 24300 hexes for Volume 1 (Volume 1).
Volume 1 (Volume 1) meshing completed using scheme: submap

Meshing time: 0.140000 
Journaled Command: mesh volume 1

Trelis>
Trelis>#cubit.cmd('pause')
Trelis>
Trelis>## bottom volume
Trelis>#cubit.cmd('volume 5 size 4785.71')
Trelis>volume 5 size 4500.
Journaled Command: volume 5 size 4500

Trelis>mesh volume 5
Volume 5 (Volume 5) meshing scheme automatically set to submap.
Matching intervals successful.
Meshing Volume 5 (Volume 5)
Generated 240 faces for Surface 21 (Surface 21).
Generated 240 faces for Surface 22 (Surface 22).
Generated 240 faces for Surface 23 (Surface 23).
Generated 240 faces for Surface 24 (Surface 24).
Generated 900 faces for Surface 25 (Surface 25).
Generated 7200 hexes for Volume 5 (Volume 5).
Volume 5 (Volume 5) meshing completed using scheme: submap

Meshing time: 0.050000 
Journaled Command: mesh volume 5

Trelis>
Trelis># draw/update mesh lines for visualization
Trelis># this will draw also the tripling layer mesh lines
Trelis>draw volume all
Trelis>
Trelis>#### End of meshing
Trelis>
Trelis>###### This is boundary_definition.py of GEOCUBIT
Trelis>#..... which extracts the bounding faces and defines them into blocks
Trelis>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'boundary_definition' is not defined
Trelis>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'boundary_definition' is not defined
Trelis>
Trelis>#### Define material properties for the 3 volumes ################
Trelis>#### DEFINE MATERIAL PROPERTIES #######################
Trelis>block 1 name "elastic 1" 
ERROR: /home/chzhang/specfem3d_devel/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (98)
       No entity with ID 1 was found
ERROR: /home/chzhang/specfem3d_devel/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (98)
       No entities specified.
Trelis>block 1 attribute count 6
ERROR: /home/chzhang/specfem3d_devel/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (99)
       No entity with ID 1 was found
ERROR: /home/chzhang/specfem3d_devel/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (99)
       No entities specified.
Trelis>block 1 attribute index 1 1  
ERROR: /home/chzhang/specfem3d_devel/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (100)
       No entity with ID 1 was found
ERROR: /home/chzhang/specfem3d_devel/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (100)
       No entities specified.
Trelis>block 1 attribute index 2 2800 
ERROR: /home/chzhang/specfem3d_devel/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (101)
       No entity with ID 1 was found
ERROR: /home/chzhang/specfem3d_devel/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (101)
       No entities specified.
Trelis>block 1 attribute index 3 1500 
ERROR: /home/chzhang/specfem3d_devel/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (102)
       No entity with ID 1 was found
ERROR: /home/chzhang/specfem3d_devel/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (102)
       No entities specified.
Trelis>block 1 attribute index 4 2300 
ERROR: /home/chzhang/specfem3d_devel/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (103)
       No entity with ID 1 was found
ERROR: /home/chzhang/specfem3d_devel/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (103)
       No entities specified.
Trelis>block 1 attribute index 5 9000.0 
ERROR: /home/chzhang/specfem3d_devel/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (104)
       No entity with ID 1 was found
ERROR: /home/chzhang/specfem3d_devel/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (104)
       No entities specified.
Trelis>block 1 attribute index 6 0 
ERROR: /home/chzhang/specfem3d_devel/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (105)
       No entity with ID 1 was found
ERROR: /home/chzhang/specfem3d_devel/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (105)
       No entities specified.
Trelis>
Trelis>block 2 name "elastic 2" 
ERROR: /home/chzhang/specfem3d_devel/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (107)
       No entity with ID 2 was found
ERROR: /home/chzhang/specfem3d_devel/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (107)
       No entities specified.
Trelis>block 2 attribute count 6
ERROR: /home/chzhang/specfem3d_devel/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (108)
       No entity with ID 2 was found
ERROR: /home/chzhang/specfem3d_devel/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (108)
       No entities specified.
Trelis>block 2 attribute index 1 2  
ERROR: /home/chzhang/specfem3d_devel/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (109)
       No entity with ID 2 was found
ERROR: /home/chzhang/specfem3d_devel/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (109)
       No entities specified.
Trelis>block 2 attribute index 2 7500 
ERROR: /home/chzhang/specfem3d_devel/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (110)
       No entity with ID 2 was found
ERROR: /home/chzhang/specfem3d_devel/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (110)
       No entities specified.
Trelis>block 2 attribute index 3 4300 
ERROR: /home/chzhang/specfem3d_devel/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (111)
       No entity with ID 2 was found
ERROR: /home/chzhang/specfem3d_devel/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (111)
       No entities specified.
Trelis>block 2 attribute index 4 3200 
ERROR: /home/chzhang/specfem3d_devel/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (112)
       No entity with ID 2 was found
ERROR: /home/chzhang/specfem3d_devel/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (112)
       No entities specified.
Trelis>block 2 attribute index 5 9000.0 
ERROR: /home/chzhang/specfem3d_devel/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (113)
       No entity with ID 2 was found
ERROR: /home/chzhang/specfem3d_devel/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (113)
       No entities specified.
Trelis>block 2 attribute index 6 0 
ERROR: /home/chzhang/specfem3d_devel/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (114)
       No entity with ID 2 was found
ERROR: /home/chzhang/specfem3d_devel/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (114)
       No entities specified.
Trelis>
Trelis>block 3 name "elastic 3" 
ERROR: /home/chzhang/specfem3d_devel/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (116)
       No entity with ID 3 was found
ERROR: /home/chzhang/specfem3d_devel/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (116)
       No entities specified.
Trelis>block 3 attribute count 6
ERROR: /home/chzhang/specfem3d_devel/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (117)
       No entity with ID 3 was found
ERROR: /home/chzhang/specfem3d_devel/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (117)
       No entities specified.
Trelis>block 3 attribute index 1 3  
ERROR: /home/chzhang/specfem3d_devel/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (118)
       No entity with ID 3 was found
ERROR: /home/chzhang/specfem3d_devel/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (118)
       No entities specified.
Trelis>block 3 attribute index 2 7500 
ERROR: /home/chzhang/specfem3d_devel/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (119)
       No entity with ID 3 was found
ERROR: /home/chzhang/specfem3d_devel/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (119)
       No entities specified.
Trelis>block 3 attribute index 3 4300 
ERROR: /home/chzhang/specfem3d_devel/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (120)
       No entity with ID 3 was found
ERROR: /home/chzhang/specfem3d_devel/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (120)
       No entities specified.
Trelis>block 3 attribute index 4 3200 
ERROR: /home/chzhang/specfem3d_devel/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (121)
       No entity with ID 3 was found
ERROR: /home/chzhang/specfem3d_devel/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (121)
       No entities specified.
Trelis>block 3 attribute index 5 9000.0 
ERROR: /home/chzhang/specfem3d_devel/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (122)
       No entity with ID 3 was found
ERROR: /home/chzhang/specfem3d_devel/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (122)
       No entities specified.
Trelis>block 3 attribute index 6 0 
ERROR: /home/chzhang/specfem3d_devel/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (123)
       No entity with ID 3 was found
ERROR: /home/chzhang/specfem3d_devel/specfem3d/EXAMPLES/layered_halfspace/2lay_mesh_boundary_fig8.py (123)
       No entities specified.
Trelis>
Trelis>export mesh "top.e" dimension 3 overwrite

Using ExodusII API version 6.05 and DB version 6.05 to export "top.e".

Executive Exodus summary:
  Number of dimensions     = 3
  Number of element blocks = 3
  Number of sidesets       = 0
  Number of nodesets       = 0
  Number of bc sets        = 1
  Number of elements       = 70200
  Number of nodes          = 76819

Finished writing top.e
Journaled Command: export mesh "top.e" dimension 3 overwrite

Trelis>save as "meshing.cub" overwrite

Exported:   3 Volumes

Successfully saved CUBIT file 'meshing.cub'
Journaled Command: save as "meshing.cub" overwrite

Trelis>
Trelis>#### Export to SPECFEM3D format using cubit2specfem3d.py of GEOCUBIT
Trelis>
Trelis>
Trelis>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'cubit2specfem3d' is not defined
Trelis>
Trelis># all files needed by SCOTCH are now in directory MESH

**Comment by komatits** [comment]
Probably just a missing path in your .bash_profile file: add something like 

# for CUBIT and GeoCUBIT
setenv GEOCUBITHOME /home/komatits/codes/specfem3d/CUBIT_GEOCUBIT
setenv CUBITHOME /opt/cubit
setenv CUBITDIR /opt/cubit
setenv PYTHONPATH /opt/cubit:/opt/cubit/bin:/home/komatits/codes/specfem3d/CUBIT_GEOCUBIT:/home/komatits/codes/specfem3d/CUBIT_GEOCUBIT/geocubitlib
