### ISSUE TITLE
gfortran flags for unused variables

### ISSUE THREAD

**Issue by luet** [geodynamics/specfem3d#528]
It looks like the newer gfortran (4.8.2) doesn't catch unused variables when the flag `-Wunused` is set. But if we change it to `-Wunused-parameter` it  works. At least I can catch some from 0d5ae80:

    constants_meshfem3D.h:50.30:
    Included at src/meshfem3D/check_mesh_quality.f90:391:

    integer, parameter :: BOTTOM = 5
                              1
    Warning: Unused parameter 'bottom' declared at (1)
       constants_meshfem3D.h:63.54:
        Included at src/meshfem3D/check_mesh_quality.f90:391:
    
      double precision, parameter :: DEGREES_PER_CELL_MOHO = 0.1d0
                                                          1
        Warning: Unused parameter 'degrees_per_cell_moho' declared at (1)
        constants_meshfem3D.h:56.60:
        Included at src/meshfem3D/check_mesh_quality.f90:391:
    
          double precision, parameter :: DEGREES_PER_CELL_TOPO_SOCAL = 5.d0 / 1000.d0
                                                                1
        Warning: Unused parameter 'degrees_per_cell_topo_socal' declared at (1)
        constants_meshfem3D.h:152.49:
        Included at src/meshfem3D/check_mesh_quality.f90:391:
    
      double precision, parameter :: DEPTH_16km_SOCAL = -16000.d0
                                                     1 
        Warning: Unused parameter 'depth_16km_socal' declared at (1)
        constants_meshfem3D.h:151.50:
        Included at src/meshfem3D/check_mesh_quality.f90:391:
    
       double precision, parameter :: DEPTH_5p5km_SOCAL = -5500.d0
                                                      1
        Warning: Unused parameter 'depth_5p5km_socal' declared at (1)
        constants_meshfem3D.h:153.49:
        Included at src/meshfem3D/check_mesh_quality.f90:391:
    
      double precision, parameter :: DEPTH_MOHO_SOCAL = -32000.d0
                                                     1
        Warning: Unused parameter 'depth_moho_socal' declared at (1)
        constants_meshfem3D.h:103.47:
        Included at src/meshfem3D/check_mesh_quality.f90:391:
    
      double precision, parameter :: END_X_GOCAD_HR = ORIG_X_GOCAD_HR + SPACING_X_G
                                                   1
       Warning: Unused parameter 'end_x_gocad_hr' declared at (1)
        constants_meshfem3D.h:88.47:
            Included at src/meshfem3D/check_mesh_quality.f90:391:
    
      double precision, parameter :: END_X_GOCAD_MR = ORIG_X_GOCAD_MR + SPACING_X_G
                                                   1
        Warning: Unused parameter 'end_x_gocad_mr' declared at (1) 
        constants_meshfem3D.h:104.47:
        Included at src/meshfem3D/check_mesh_quality.f90:391:
    
      double precision, parameter :: END_Y_GOCAD_HR = ORIG_Y_GOCAD_HR + SPACING_Y_G
                                                   1
        Warning: Unused parameter 'end_y_gocad_hr' declared at (1)
        constants_meshfem3D.h:89.47:
            Included at src/meshfem3D/check_mesh_quality.f90:391:
    
          double precision, parameter :: END_Y_GOCAD_MR = ORIG_Y_GOCAD_MR + SPACING_Y_G
                                                   1
        Warning: Unused parameter 'end_y_gocad_mr' declared at (1)
        Fatal Error: Error count reached limit of 10.
       make: *** [obj/check_mesh_quality.mesh.o] Error 1

**Comment by komatits** [comment]
Hi David,

Yes, but that is not the same, and unused parameters are normal and we 
should not display warnings about them; only unused variables are a problem.

Thanks,
Dimitri.

On 06/04/2015 06:37 PM, David Luet wrote:
> It looks like the newer gfortran (4.8.2) doesn't catch unused variables
> when the flag |-Wunused| is set. But if we change it to
> |-Wunused-parameter| it works. At least I can catch some from 0d5ae80
> <https://github.com/geodynamics/specfem3d/commit/0d5ae8078403cd471ec2660d87f30988442131ec>:
>
> |constants_meshfem3D.h:50.30:
> Included at src/meshfem3D/check_mesh_quality.f90:391:
>
> integer, parameter :: BOTTOM = 5
>                            1
> Warning: Unused parameter 'bottom' declared at (1)
>     constants_meshfem3D.h:63.54:
>      Included at src/meshfem3D/check_mesh_quality.f90:391:
>
>    double precision, parameter :: DEGREES_PER_CELL_MOHO = 0.1d0
>                                                        1
>      Warning: Unused parameter 'degrees_per_cell_moho' declared at (1)
>      constants_meshfem3D.h:56.60:
>      Included at src/meshfem3D/check_mesh_quality.f90:391:
>
>        double precision, parameter :: DEGREES_PER_CELL_TOPO_SOCAL = 5.d0 / 1000.d0
>                                                              1
>      Warning: Unused parameter 'degrees_per_cell_topo_socal' declared at (1)
>      constants_meshfem3D.h:152.49:
>      Included at src/meshfem3D/check_mesh_quality.f90:391:
>
>    double precision, parameter :: DEPTH_16km_SOCAL = -16000.d0
>                                                   1
>      Warning: Unused parameter 'depth_16km_socal' declared at (1)
>      constants_meshfem3D.h:151.50:
>      Included at src/meshfem3D/check_mesh_quality.f90:391:
>
>     double precision, parameter :: DEPTH_5p5km_SOCAL = -5500.d0
>                                                    1
>      Warning: Unused parameter 'depth_5p5km_socal' declared at (1)
>      constants_meshfem3D.h:153.49:
>      Included at src/meshfem3D/check_mesh_quality.f90:391:
>
>    double precision, parameter :: DEPTH_MOHO_SOCAL = -32000.d0
>                                                   1
>      Warning: Unused parameter 'depth_moho_socal' declared at (1)
>      constants_meshfem3D.h:103.47:
>      Included at src/meshfem3D/check_mesh_quality.f90:391:
>
>    double precision, parameter :: END_X_GOCAD_HR = ORIG_X_GOCAD_HR + SPACING_X_G
>                                                 1
>     Warning: Unused parameter 'end_x_gocad_hr' declared at (1)
>      constants_meshfem3D.h:88.47:
>          Included at src/meshfem3D/check_mesh_quality.f90:391:
>
>    double precision, parameter :: END_X_GOCAD_MR = ORIG_X_GOCAD_MR + SPACING_X_G
>                                                 1
>      Warning: Unused parameter 'end_x_gocad_mr' declared at (1)
>      constants_meshfem3D.h:104.47:
>      Included at src/meshfem3D/check_mesh_quality.f90:391:
>
>    double precision, parameter :: END_Y_GOCAD_HR = ORIG_Y_GOCAD_HR + SPACING_Y_G
>                                                 1
>      Warning: Unused parameter 'end_y_gocad_hr' declared at (1)
>      constants_meshfem3D.h:89.47:
>          Included at src/meshfem3D/check_mesh_quality.f90:391:
>
>        double precision, parameter :: END_Y_GOCAD_MR = ORIG_Y_GOCAD_MR + SPACING_Y_G
>                                                 1
>      Warning: Unused parameter 'end_y_gocad_mr' declared at (1)
>      Fatal Error: Error count reached limit of 10.
>     make: *** [obj/check_mesh_quality.mesh.o] Error 1
> |
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/issues/528>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by luet** [comment]
Then I am not sure why gfortran didn't catch the unused variables that you had to fix in 6dff69747.
I wonder if there isn't a problem with the Makefile. For instance:

    gfortran -g -O2 -std=f2003 -fimplicit-none -frange-check -fmax-errors=10 -pedantic -pedantic-errors -
    Waliasing -Wampersand -Wcharacter-truncation -Wline-truncation -Wsurprising -Wno-tabs -
    Wunderflow -ffpe-trap=invalid,zero,overflow -Wunused -Werror -O3  -J./obj -I./obj -I.  -I./setup  -c -o 
    obj/exit_mpi.shared.o src/shared/exit_mpi.f90

Which optimization flag are we using? Is it `-O2` or `-O3`?

**Comment by komatits** [comment]
-g -O2 is added automatically by the "configure" script for some reason; 
that should be removed

The rest is what we have in flags.guess and is normal.

Dimitri.

On 06/04/2015 07:12 PM, David Luet wrote:
> Then I am not sure why gfortran didn't catch the unused variables that
> you had to fix in 6dff697
> <https://github.com/geodynamics/specfem3d/commit/6dff6974734f7aebc091a21606050063d8c3bf9c>.
> I wonder if there isn't a problem with the Makefile. For instance:
>
> |gfortran -g -O2 -std=f2003 -fimplicit-none -frange-check -fmax-errors=10 -pedantic -pedantic-errors -
> Waliasing -Wampersand -Wcharacter-truncation -Wline-truncation -Wsurprising -Wno-tabs -
> Wunderflow -ffpe-trap=invalid,zero,overflow -Wunused -Werror -O3  -J./obj -I./obj -I.  -I./setup  -c -o
> obj/exit_mpi.shared.o src/shared/exit_mpi.f90
> |
>
> Which optimization flag are we using? Is it |-O2| or |-O3|?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/issues/528#issuecomment-108978931>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by Abdij** [comment]
Dear Sir 
please try to help me to configure SPECFEM3D globe v7.0.0, i have all the required packages. i read the installation manual 100 times and couldnt install the package. is there a step by step guide u could provide me. i am using ubuntu 16.04. please this is urgent.

**Comment by komatits** [comment]
Dear Abdij,

To compile the code with gfortran, just type this:

./configure
make all

Best regards,
Dimitri.

On 09/06/2016 16:06, Abdij wrote:
> Dear Sir
> please try to help me to configure SPECFEM3D globe v7.0.0, i have all
> the required packages. i read the installation manual 100 times and
> couldnt install the package. is there a step by step guide u could
> provide me. i am using ubuntu 16.04. please this is urgent.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/geodynamics/specfem3d/issues/528#issuecomment-224905207>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AFjDKWyxVGnZ-s8ZC8h2letW51Il7_u0ks5qKB32gaJpZM4E4e7E>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr
