### ISSUE TITLE
most examples in EXAMPLES/fault_examples are broken

### ISSUE THREAD

**Issue by komatits** [geodynamics/specfem3d#532]
most examples in EXAMPLES/fault_examples are broken, the mesh cannot be created any more using "claro" from the CUBIT/TRELIS package, the mesh created contains points but does not contain any element (the list of elements created in the "MESH" directory is empty).
Could be a problem in EXPORT2SPECFEM from the GEOCUBIT library or something like that.
I thus renamed the directories of all the examples that do not work any more (i.e. all but one).

@kbai  @jpampuero @casarotti

**Comment by jpampuero** [comment]
The examples that do not work have:
  entities=['face']
  define_boundaries(entities,xmin,xmax,ymin,ymax,zmin,zmax)
whereas the ones that work have:
  boundary_definition.entities=['face'] 
  boundary_definition.define_bc(boundary_definition.entities,parallel=True) 
Once could try replacing those lines. I don't have TRELIS though. Can someone else try this fix?

**Comment by komatits** [comment]
Hi Jean-Paul and Kangchen,

Thanks a lot! I will try it (I have TRELIS).

Dimitri.

On 06/06/2015 07:35 AM, Jean Paul Ampuero wrote:
> The examples that do not work have:
> entities=['face']
> define_boundaries(entities,xmin,xmax,ymin,ymax,zmin,zmax)
> whereas the ones that work have:
> boundary_definition.entities=['face']
> boundary_definition.define_bc(boundary_definition.entities,parallel=True)
> Once could try replacing those lines. I don't have TRELIS though. Can
> someone else try this fix?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/issues/532#issuecomment-109531353>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by komatits** [comment]
@kbai @jpampuero @casarotti 
I have just tried, the new version works better than before, but there is still one small problem to fix:

CUBIT> #### Export to SPECFEM3D format using cubit2specfem3d.py of GEOCUBIT 
CUBIT>  
CUBIT> 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/komatits/codes/specfem3d/CUBIT_GEOCUBIT/geocubitlib/cubit2specfem3d.py", line 1106, in export2SPECFEM3D
    sem_mesh=mesh(hex27,cpml,cpml_size,top_absorbing)
  File "specfem3d/CUBIT_GEOCUBIT/geocubitlib/cubit2specfem3d.py", line 382, in __init__
    self.block_definition()
  File "specfem3d/CUBIT_GEOCUBIT/geocubitlib/cubit2specfem3d.py", line 459, in block_definition
    if qk < 0 or qmu < 0:
UnboundLocalError: local variable 'qk' referenced before assignment

**Comment by komatits** [comment]
Hi Kangchen @kbai,

Did you run the examples after fixing the scripts, i.e. did you try the fixed version of the scripts? here on my machines they crash both with CUBIT v13 and with TRELIS v15, with the same message (below). Thus please test them after fixing them and before committing the changes.

Thanks,
Dimitri.

Trelis>
len(Au): 89011
len(Ad): 0
Number of elements for each fauld side up and down do not concide
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/komatits/codes/specfem3d/CUBIT_GEOCUBIT/geocubitlib/save_fault_nodes_elements.py", line 23, in __init__
    sys.exit('goodbye')
NameError: global name 'sys' is not defined

**Comment by kbai** [comment]
Hi Dimitri @komatits 
Sorry, I tested only one of them before due to the long run time. I fixed the mismatching problem mentioned in your last comment and tested all the examples successfully with a coarser element size  under CUBIT 13.

Kangchen

**Comment by komatits** [comment]
Hi Kangchen,

Thanks! They all work fine now (also with TRELIS 15, I checked (at full 
resolution)), except the small one (tpv5), which used to work but now says:

CUBIT> # Material properties in concordance with tpv5 benchmark.
CUBIT>
CUBIT> block 1 name "elastic 1"
ERROR: No entity with ID 1 was found
ERROR: No entities specified.
CUBIT> block 1 attribute count 5
ERROR: No entity with ID 1 was found
ERROR: No entities specified.
CUBIT> block 1 attribute index 1 1
ERROR: No entity with ID 1 was found
ERROR: No entities specified.
CUBIT> block 1 attribute index 2 6000
ERROR: No entity with ID 1 was found
ERROR: No entities specified.
CUBIT> block 1 attribute index 3 3464
ERROR: No entity with ID 1 was found


Could you fix it?

Thanks,
Dimitri.


On 06/07/2015 07:31 PM, Kangchen Bai wrote:
> Hi Dimitri @komatits <https://github.com/komatits>
> Sorry, I tested only one of them before due to the long run time. I
> fixed the mismatching problem mentioned in your last comment and tested
> all the examples successfully with a coarser element size under CUBIT 13.
>
> Kangchen
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/issues/532#issuecomment-109778797>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by komatits** [comment]
Fixed by @kbai .
