### ISSUE TITLE
Problem in elastic modeling for marine case when tomo-file is used

### ISSUE THREAD

**Issue by DmBorisov** [geodynamics/specfem3d#606]
Hi,
There is a problem for elastic modeling when "MODEL = tomo" is used in marine case. The output_mesher.txt shows no acoustic elements even though the water layer is properly defined. Consequently, the pressure data, which is generated and recorded in water layer, is zero. There is no problem when SEP-file format is used.

**Comment by komatits** [comment]
I assume this is now fixed?
Dimitri.
@DmBorisov @casarotti @danielpeter @vmont
