### ISSUE TITLE
Simultaneous sources

### ISSUE THREAD

**Issue by jbehura** [geodynamics/specfem3d#611]
Is there a way to specify multiple simultaneous sources (with different source signatures)? I do not see that option for forward propagation. I believe it should be easily implementable given the computation of adjoint wavefield is possible.

**Comment by komatits** [comment]
You can have several sources (as many as you want) simultaneously, just adding them one after the other in the DATA/SOURCE file. They can have different starting times (that is what people use for large earthquakes, described by many different sub-sources that start at different times). They currenly all use the same kind of source time function (i.e. if one is a Ricker, all of them are Rickers); however that would be easy to change (adding a few lines in the source code). 

Best regards, 

Dimitri.

**Comment by jbehura** [comment]
Hi Dimitri,

Thanks for the quick response and clarification. I will try to incorporate the different source time functions in the code.

Cheers,
Jyoti

**Comment by komatits** [comment]
Hi Jyoti,

Thanks! That would be very useful. When you are done please do not 
hesitate to commit to changes to the official Git source code (in the 
"devel" branch). Here is how to do that: 
https://github.com/geodynamics/specfem3d/wiki/Using-Git-for-SPECFEM

Thanks,
Dimitri.

On 09/04/2015 04:01 PM, jbehura wrote:
> Hi Dimitri,
>
> Thanks for the quick response and clarification. I will try to
> incorporate the different source time functions in the code.
>
> Cheers,
> Jyoti
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/issues/611#issuecomment-137745243>.Web
> Bug from
> https://github.com/notifications/beacon/AFjDKcLnBwUlxTkyjZzCPMe9p_cA-LJPks5ouZuzgaJpZM4F3nKT.gif
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr
