### ISSUE TITLE
compilation failed

### ISSUE THREAD

**Issue by kbai** [geodynamics/specfem3d#631]
src/specfem3D/integrals_on_whole_domain.f90(31): error #5508: Declaration of routine 'SURFACE_OR_VOLUME_INTEGRAL_ON_WHOLE_DOMAIN' conflicts with a previous declaration

I am using mpiifort/ifort compiler.

**Comment by komatits** [comment]
Hi Clément,

Coming from your new KH integrals maybe? Please doublecheck.

Thanks,
Dimitri.

On 09/22/2015 10:18 PM, Kangchen Bai wrote:
> src/specfem3D/integrals_on_whole_domain.f90(31): error #5508:
> Declaration of routine 'SURFACE_OR_VOLUME_INTEGRAL_ON_WHOLE_DOMAIN'
> conflicts with a previous declaration
>
> I am using mpiifort/ifort compiler.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/issues/631>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by durochat** [comment]
I don't have any problem of compilation on my side, and this changes passed the buildbot, with ifort and ifort mpi. Can you compile it with debug mode to have more information of the compilation error please ?

**Comment by komatits** [comment]
It is probably SURFACE_OR_VOLUME_INTEGRAL_ON_WHOLE_DOMAIN that is 
declared in a module and then declared again in 
src/specfem3D/integrals_on_whole_domain.f90

Dimitri

On 09/23/2015 02:32 PM, Clément Durochat wrote:
> I don't have any problem of compilation on my side, and this changes
> passed the buildbot, with ifort and ifort mpi. Can you compile it with
> debug mode to have more information of the compilation error please ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/issues/631#issuecomment-142584969>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by durochat** [comment]
In which module did you see that ? I never put this routine in a module, and with grep I don't see it in any module... ?

**Comment by durochat** [comment]
There is just a constant in constants.h.in, called "Surf_or_vol_integral", but the problem can't came from here.

**Comment by durochat** [comment]
Are you sure that your last gi pull was ok ?

**Comment by luet** [comment]
Do you have the same problem with mpif90 instead of mpiifort?
What version of the Intel compiler are you using?
Can you send us the output of:
$ mpiifort -v
$ ifort -v

Thanks,
David

On Wed, Sep 23, 2015 at 9:04 AM, Clément Durochat <notifications@github.com>
wrote:

> Are you sure that your last gi pull was ok ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/issues/631#issuecomment-142592422>
> .
>



-- 
David Luet
Linux Administrator/Software & Programming Analyst
Department of Geosciences & PICSciE
Princeton University

**Comment by luet** [comment]
It seems to work for me. Here is what I have:

    $ mpiifort -v
    mpiifort for the Intel(R) MPI Library 5.0 Update 3 for Linux*
    Copyright(C) 2003-2015, Intel Corporation.  All rights reserved.
    ifort version 14.0.0

And here is what I do:

    $ git clone --branch=devel git@github.com:geodynamics/specfem3d.git
    $ cd specfem3d
    $ git show
      commit 29bac00b65cbe0aff8d2259fee05d9133070f83c
      ....
    $ git submodule init
    $ git submodule update
    $ aclocal -I m4
    $ autoconf -I m4
    $ ./configure FC=ifort CC=icc MPIFC=mpiifort MPICC=mpiicpc --with-mpi
    $ make -j 8

Can you do the exact same steps and send us the output?
Thanks,
David
