### ISSUE TITLE
bug in in house mesher

### ISSUE THREAD

**Issue by specfem3d-zhang-ksu** [geodynamics/specfem3d#643]
I mesh a big model by using many MPI processes. As I gradually reduce the number of MPI processes, it will get an exit code 139 error, as shown below 

   running mesher...

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 27636 RUNNING AT sth104
=   EXIT CODE: 139
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================
[proxy:0:1@sth102] HYD_pmcd_pmip_control_cmd_cb (pm/pmiserv/pmip_cb.c:885): assert (!closed) failed
[proxy:0:1@sth102] HYDT_dmxu_poll_wait_for_event (tools/demux/demux_poll.c:76): callback returned error status
[proxy:0:1@sth102] main (pm/pmiserv/pmip.c:206): demux engine error waiting for event
[proxy:0:4@sth111] HYD_pmcd_pmip_control_cmd_cb (pm/pmiserv/pmip_cb.c:885): assert (!closed) failed
[proxy:0:4@sth111] HYDT_dmxu_poll_wait_for_event (tools/demux/demux_poll.c:76): callback returned error status
[proxy:0:4@sth111] main (pm/pmiserv/pmip.c:206): demux engine error waiting for event
[mpiexec@master] HYDT_bscu_wait_for_completion (tools/bootstrap/utils/bscu_wait.c:76): one of the processes terminated badly; aborting
[mpiexec@master] HYDT_bsci_wait_for_completion (tools/bootstrap/src/bsci_wait.c:23): launcher returned error waiting for completion
[mpiexec@master] HYD_pmci_wait_for_completion (pm/pmiserv/pmiserv_pmci.c:218): launcher returned error waiting for completion
[mpiexec@master] main (ui/mpich/mpiexec.c:344): process manager error waiting for completion

If I open the output_meshfem3D file,  I find it just stop below 
 **************************
 creating mesh in the model
 **************************

**Comment by QuLogic** [comment]
139 is a segmentation fault. You can compile with `--enable-debug` and hopefully it will give you a full backtrace.
