### ISSUE TITLE
FORCESOLUTION may have a problem

### ISSUE THREAD

**Issue by komatits** [geodynamics/specfem3d#652]
From: Dimitri Komatitsch  to @bottero and @bencesolymosi 

It is true that for now this option is mostly unused and thus untested (in geophysics most people use a CMTSOLUTION, and in ocean acoustics most of the time the source is in the fluid
rather than in the solid).

Bence will soon use it though.

Let me thus open a new "Git issue" about it and cut and paste your
emails below in it, so that we remember to do it in a few months.

Thanks,
Dimitri.

On 11/09/2015 10:29 AM, bottero wrote:
> Hello Florian,
> You are right FORCESOLUTION option is a mess (not through the fault of
> Bence nor me)! For the moment I don't use it either so I won't fix it.
> When I'll need it (probably within the next 6 monthes) I'll fix it and
> commit my changes if it has not been done before.
>
> Thank you for your feed back
>
> Alexis
>
> On 09/11/2015 09:55, Florian Schumacher wrote:
>> Hallo Alexis and Solymosi,
>>
>> referring to Dimitris answer below, I'd like to point out, that I am not
>> sure whether in ALL calls to comp_source_time_function_gauss() the
>> hard-coded value of 5.d0*DT should be replaced by hdur_gaussian(isource)
>> and I prefer you guys to have a look at it. I will not commit any
>> changes to the repository.
>>
>> I've also noticed that in compute_add_sources_acoustic.f90 and
>> compute_add_sources_poroelastic.f90 (in devel branch), there are already
>> some calls to comp_source_time_function_gauss() where 5.d0*DT was
>> replaced by hdur_gaussian(isource) , and other calls where still 5.d0*DT
>> remains. Is this mixture intended?
>>
>> Thanks!
>> Florian
>>
>>
>> -------- Ursprüngliche Nachricht --------
>> Von: Dimitri Komatitsch 
>> Gesendet: 8. November 2015 23:30:00 MEZ
>> An: Florian Schumacher 
>> Betreff: Re: [CIG-SEISMO] SPECFEM3d_Cartesian , using point force with
>> gaussian stf
>>
>>
>> Hi Florian,
>>
>> Yes, I committed it without checking it, I thought the issue was fully
>> fixed already. Let me thus cc Alexis Bottero and Bence Solymosi, who are
>> currently both using the FORCESOLUTION option, to see how this could be
>> fixed.
>>
>> (or even better, if you know how to fix it yourself please do not
>> hesitate to do it and then either email me the file or follow
>> https://github.com/geodynamics/specfem3d/wiki/Using-Git-for-SPECFEM to
>> commit it to Git directly)
>>
>> Thanks again!
>> Cheers,
>>
>> Dimitri.
>>
>> On 11/08/2015 06:47 PM, Florian Schumacher wrote:
>>> Hallo Dimitri,
>>>
>>> preparing the next ASKI release, I noticed that your commit 4bc3dd6 to
>>> the SPECFEM3D_Cartesian devel branch on 3 Sep 2015 based on my
>>> suggestions only makes partially sense to me:
>>> https://github.com/geodynamics/specfem3d/commit/4bc3dd673407b950e0372116a7d6b2029d03ea2c#diff-e0c13ae549ca95a62c20939960769fdf
>>>
>>>
>>>
>>> It seems that you committed a 1-to-1 copy of the file
>>> compute_add_sources_viscoelastic.f90 that I attached to my email. As
>>> stated below, I was not sure about whether to replace 5.d0*DT by
>>> hdur_gaussian(isource) in ALL calls of comp_source_time_function_gauss()
>>> . That is why on 3 lines I left the original value of 5.d0*DT in my
>>> attached file (lines 507, 687, 853 in commit 4bc3dd6, in the current
>>> revision we are talking about lines 510, 691, 858). On these lines, I
>>> find that you only committed my comment
>>> "! FS FS  does it also here make sense to replace 5.d0*DT by
>>> hdur_gaussian(isource) ? looks like it"
>>> but did not modify the code in any way. This seems odd to me, unless you
>>> intended to leave my comment there since you were unsure yourself
>>> whether to apply the change.
>>>
>>> Did you leave the value of 5.d0*DT by intention for adjoint and GPU
>>> simulations? In case you did not notice my asking to have a look at it
>>> whether it makes sense to change it, I am sorry, I should have pointed
>>> out it out more clearly.
>>>
>>>
>>> Sorry to bother you again on this account.
>>>
>>> Best regards,
>>> Florian

**Comment by specfem3d-zhang-ksu** [comment]
how can I setup  FORCESOLUTION and  Par_file,  so that I convolve the caculated seismogram with a source wavelet to obtain the resulting synthetic seismogram in post-processing after the run?

**Comment by komatits** [comment]
Fixed by @vmont and @bencesolymosi ; @casarotti will confirm that the problem is fixed.
