### ISSUE TITLE
fix the PML singularity detection routine, which should be in double precision

### ISSUE THREAD

**Issue by komatits** [geodynamics/specfem3d#654]
fix the PML singularity detection routine, which should be in double precision. Otherwise people get messages such as:

"error in seperation of alpha_x, alpha_y, alpha_z in case alpha_y == alpha_z .and. alpha_x /= alpha_y" 

@vmont @xiezhinan

**Comment by komatits** [comment]
Yes, for sure that problem comes from the fact that the detection routine compares to an absolute value (an absolute threshold) instead of a relative one; I would thus suggest making the comparison relative instead of absolute, and also to be safe doing it in double precision instead of single.

Thank you,
Best regards,

Dimitri.

**Comment by komatits** [comment]
@xiezhinan  Don't you think we could simply see this as an optimization under constraint problem and write a small routine that will automatically make sure that alpha_x and alpha_y are never equal anywhere in the PML corners (and same thing for alpha_z and so on)?

**Comment by xiezhinan** [comment]
Dear Dimitri, Dear all,


The current way of treating the signularities can be simplified to a subroutine.
For optimization under constraint problem, What we want is following:
Make sure that alpha_x /= alpha_y /= alpha_z everywhere.
Moreover we should also make beta_x  /= alpha_y /= alpha_z , beta_y  /= alpha_x /= alpha_y and beta_z  /= alpha_x /= alpha_y everywhere.


Then how to define the optimization?


Thank you so much.
Best regards,
Zhinan












At 2015-11-27 05:09:34, "Dimitri Komatitsch" <notifications@github.com> wrote:


@xiezhinan Don't you think we could simply see this as an optimization under constraint problem and write a small routine that will automatically make sure that alpha_x and alpha_y are never equal anywhere in the PML corners (and same thing for alpha_z and so on)?

**Comment by komatits** [comment]
Dear Zhinan,

What I mentioned below is an old comment from last month, the 
modification you committed last week could be sufficient. Thus let us 
ignore my comment below for now and only come back to it if the PML 
singularity code still fails in some cases.

Thank you,
Best regards,

Dimitri.

On 11/26/2015 11:52 PM, Xie Zhinan wrote:
> Dear Dimitri, Dear all,
>
>
> The current way of treating the signularities can be simplified to a
> subroutine.
> For optimization under constraint problem, What we want is following:
> Make sure that alpha_x /= alpha_y /= alpha_z everywhere.
> Moreover we should also make beta_x /= alpha_y /= alpha_z , beta_y /=
> alpha_x /= alpha_y and beta_z /= alpha_x /= alpha_y everywhere.
>
>
> Then how to define the optimization?
>
>
> Thank you so much.
> Best regards,
> Zhinan
>
>
>
>
>
>
>
>
>
>
>
>
> At 2015-11-27 05:09:34, "Dimitri Komatitsch" <notifications@github.com>
> wrote:
>
>
> @xiezhinan Don't you think we could simply see this as an optimization
> under constraint problem and write a small routine that will
> automatically make sure that alpha_x and alpha_y are never equal
> anywhere in the PML corners (and same thing for alpha_z and so on)?
>
> —
> Reply to this email directly or view it on GitHub.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/issues/654#issuecomment-160001763>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by komatits** [comment]
Seems to be fixed already, since nobody is reporting instabilities any more; let me wait for a couple more months, and then I will close the issue. Vadim @vmont is going to further clean and optimize the existing CPML code anyway, to make it much faster and also much easier to maintain.
Let me cc @homnath @jas11 and @dborissov , since they are also cleaning the CPML code (to them: please email your contributions to Vadim, and Vadim will finish the optimization and merge the whole set of modifications). Thanks.

**Comment by komatits** [comment]
Done by Zhinan @xiezhinan .
