### ISSUE TITLE
use SolvOpt for attenuation coefficients instead of the old way

### ISSUE THREAD

**Issue by komatits** [geodynamics/specfem3d#742]
The new way to get the relaxation times for attenuation, which is described in http://komatitsch.free.fr/preprints/GJI_Lombard_2016.pdf , is called SolvOpt and used in SPECFEM2D, but not yet cut and pasted in SPECFEM3D and SPECFEM3D_GLOBE.

(cutting and pasting the call to the routine that computes tau_epsilon and tau_sigma).

**Comment by JimmyZJU** [comment]
I've run a new example by myself in old version V2.0.2.tar.gz[2012-07-05] , but the output of SEMA, SEMV, SEMD files in OUTPUT_FILES is unreasonable. **The acceleration, velocity and displacement did't approach to zero at the end of simulation.** It seems that there is something wrong about attenuation settings. How to change the attenuation coefficients or other settings to get the reasonable output? The nummaterial_velocity_file, CMTSOLUTION, Par_file and a part of proc000000_attenuation.vtk are as fllowing.

**nummaterial_velocity_file:**
2 1 2200.000000 1732.000000 1500.000000 9999.000000 30.000000 0

**CMTSOLUTION:**
PDE 2016 06 07 00 00 00.00 300 0 300 4.2 4.2 hillrock_earthquake
event name: hillrock_earthquake
time shift: 0.0000
half duration: 0.0
latitude: 300.0
longitude: 0.0
depth: 0.7
Mrr: 1.000000e+23
Mtt: 1.000000e+23
Mpp: 1.000000e+23
Mrt: 0.000000
Mrp: 0.000000
Mtp: 0.000000

**Par_flie:**
#simulation input parameters
#forward or adjoint simulation
#1 = forward, 2 = adjoint, 3 = both simultaneously
SIMULATION_TYPE = 1

#0 = earthquake simulation, 1/2/3 = three steps in noise simulation
NOISE_TOMOGRAPHY = 0

SAVE_FORWARD = .false.

#UTM projection parameters
UTM_PROJECTION_ZONE = 11
SUPPRESS_UTM_PROJECTION = .true.

#number of MPI processors
NPROC = 4

#time step parameters
NSTEP = 40000
DT = 4.5E-04

#models:
#available options are:
#default (model parameters described by mesh properties)
#1D models available are: 
#1d_prem,1d_socal,1d_cascadia
#3D models available are: 
#aniso,external,gll,salton_trough,tomo
MODEL = default
#parameters describing the model
OCEANS = .false.
TOPOGRAPHY = .false.
ATTENUATION = .true.
FULL_ATTENUATION_SOLID = .false.
USE_OLSEN_ATTENUATION = .false.
ANISOTROPY = .false.

#absorbing boundary conditions for a regional simulation
ABSORBING_CONDITIONS = .true.

#save AVS or OpenDX movies
MOVIE_SURFACE = .false.
MOVIE_VOLUME = .false.
NTSTEP_BETWEEN_FRAMES = 200
CREATE_SHAKEMAP = .false.
SAVE_DISPLACEMENT = .false.
USE_HIGHRES_FOR_MOVIES = .false.
HDUR_MOVIE = 0.0

#save AVS or OpenDX mesh files to check the mesh
SAVE_MESH_FILES = .true.

#path to store the local database file on each node
LOCAL_PATH = ../in_out_files/DATABASES_MPI

#interval at which we output time step info and max of norm of displacement
NTSTEP_BETWEEN_OUTPUT_INFO = 5000

#interval in time steps for writing of seismograms
NTSTEP_BETWEEN_OUTPUT_SEISMOS = 10000

#interval in time steps for reading adjoint traces
NTSTEP_BETWEEN_READ_ADJSRC = 0 # 0 = read the whole adjoint sources at the same time

#print source time

PRINT_SOURCE_TIME_FUNCTION = .true.

**proc000000_attenuation.vtk:**
·······
POINT_DATA 1629745
SCALARS gll_data float
LOOKUP_TABLE default
9999.000
9999.000
9999.000
······

**Comment by komatits** [comment]
Robin Lee robin DOT lee AT pg DOT canterbury DOT ac DOT nz is working on it and is going to implement it.

**Comment by komatits** [comment]
Done.

**Comment by komatits** [comment]
However, remark from Alexis Bottero @bottero : calling SolvOpt() is much more expensive because it uses an involved nonlinear optimization process. Thus, if we do it permanently, let us probably turn it OFF by default.
cc Paul @pcristini

**Comment by komatits** [comment]
Finally not a good idea, because very expensive.

**Comment by komatits** [comment]
Etienne @EtienneBachmann will see if it is worth doing that.

**Comment by komatits** [comment]
Not really needed.
