### ISSUE TITLE
One question about "sizeprocs"

### ISSUE THREAD

**Issue by xiaomolanting** [geodynamics/specfem3d#746]
Hi, This is Long Zhang. 

When I run the default example ''simple_model" in the directory /specfem3d/EXAMPLES/meshfem3D_examples. It works when the first time I run it. After that, I run other examples in the same directory, such as socal1D. Then, I rerun the example "simple_model", one error occurs,

STOP Error: must have NPROC_XI = NPROC_ETA = 1 for a serial run
STOP Error: must have NPROC_XI = NPROC_ETA = 1 for a serial run
STOP Error: must have NPROC_XI = NPROC_ETA = 1 for a serial run
STOP Error: must have NPROC_XI = NPROC_ETA = 1 for a serial run

This error is set at the script /specfem3d/src/meshfem3D/read_mesh_parameter_file.f90. I doubt that it is related to the the argument "sizeprocs". I don't know how to fix it. Welcome to any help.

**Comment by komatits** [comment]
Hi Long Zhang,

You are probably running the solver without using "mpirun". Just use the 
script called run_this_example.sh instead and you should be fine.

Best regards,
Dimitri.

On 13/04/2016 12:08, xiaomolanting wrote:
> Hi, This is Long Zhang.
>
> When I run the default example ''simple_model" in the directory
> /specfem3d/EXAMPLES/meshfem3D_examples. It works when the first time I
> run it. After that, I run other examples in the same directory, such as
> socal1D. Then, I rerun the example "simple_model", one error occurs,
>
> STOP Error: must have NPROC_XI = NPROC_ETA = 1 for a serial run
> STOP Error: must have NPROC_XI = NPROC_ETA = 1 for a serial run
> STOP Error: must have NPROC_XI = NPROC_ETA = 1 for a serial run
> STOP Error: must have NPROC_XI = NPROC_ETA = 1 for a serial run
>
> This error is set at the script
> /specfem3d/src/meshfem3D/read_mesh_parameter_file.f90. I doubt that it
> is related to the the argument "sizeprocs". I don't know how to fix it.
> Welcome to any help.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem3d/issues/746>
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr
