### ISSUE TITLE
How the adjoint field constructed and interacted with regular field in specfem3D

### ISSUE THREAD

**Issue by yuefeng9330** [geodynamics/specfem3d#776]
Hi everyone,

I have some questions about the constructing of adjoint field and kernel computation when reading the source code.

The specfem3D do wave field simulation at each time step by the program iterate_time.F90. For adjoint simulation, the program firstly calculate adjoint field by calling compute_forces_viscoelastic(), and then calculate the backward/reconstructed wavefields (time reversed) by calling compute_forces_viscoelastic_backward(). After that, the adjoint acceleration field and backward displacement field are interacted to obtain Frechet kernel. by compute_kernels.f90. My question are:

1. In compute_kernels.f90, the comments say they take adjoint acceleration and forward displacement for kernel computation, which is the symmetric form of that in Tromp et al. (2005), eq. (14). I guess these two forms are equal? where can I find the reference?

2. The adjoint field at time=it is the multiplication of Green's function at time=it-jt and adjoint source at time=jt, where jt integrates from 0 to it ( see eq. 11 in Tromp et al., 2005). This integration is supposed to be done in the program compute_forces_viscoelastic(). The program compute_forces_viscoelastic() seems can both do forward and adjoint simulation. The only difference I found is that inside the subroutine compute_add_sources_viscoelastic().  However, I couldn't find how the integration (eq.11 in Tromp et al., 2005) for constructing adjoint field is done inside the code. The only one I found seems to be the corresoponding part for integration in compute_add_sources_viscoelastic.F90 is:
accel(:,iglob) = accel(:,iglob) + adj_sourcearrays(irec_local, &
NTSTEP_BETWEEN_READ_ADJSRC - mod(it-1,NTSTEP_BETWEEN_READ_ADJSRC), &
:,i,j,k)
The code seems to calculate adjoint field at time=it by the addition of Green's function at time=it and adjoint source at time=T-it+1, and jt integrating from 0 to it. Obvious, this is different from eq.11. Am I misunderstand eq.11 or the integration is done elsewhere?
3. An other question is what's the differences when generating forward displacement (source side) and adjoint Green's function (receiver side). What I can see from the code is that the forward simulation adds source time function and the adjoint simulation adds adjoint source (no source time function?). Am I right?

Can someone give some suggestions? Thank you in advance.

**Comment by komatits** [comment]
Closing this, the message should be sent to the mailing list instead (the list of issues is basically a list of bugs or future improvements).
