### ISSUE TITLE
the receiver locating process is not always accurate when SU_FORMAT and topography are both on

### ISSUE THREAD

**Issue by komatits** [geodynamics/specfem3d#781]
From Chang-Hua Zhang @specfem3d-zhang-ksu:

I have found that the SU_FORMAT receiver locating method is not accurate for some receivers if receivers are located on a topography surface. I have not figured out why.

**Comment by EtienneBachmann** [comment]
This issue should now be solved by the last commit

**Comment by komatits** [comment]
Fixed by Etienne @EtienneBachmann
