### ISSUE TITLE
making sure -DFORCE VECTORIZATION always works fine in SPECFEM3D_Cartesian using the CONTIGUOUS Fortran2008 statement

### ISSUE THREAD

**Issue by komatits** [geodynamics/specfem3d#81]
The bug below is probably not fixed yet, but we should check with Daniel Peter because he worked on this a bit in August 2013:

The vectorized version of the code (which is compiled when flag -DFORCE VECTORIZATION is used in flags.guess) can fail on some machines because it replaces multiple indices such as (i,j,k) with a 1D version (ijk,1,1). This works fine only if the array is contiguous in memory. This is always the case for static arrays (as used for instance in SPECFEM3D_GLOBE) but the Fortran norm says that it is NOT necessarily the case when dynamic memory allocation is used. Many compilers will use a continuous memory chunk, but some will not and then the vectorized code of FORCE VECTORIZATION will fail.

In Fortran 2008 this is easy to fix by using the "CONTIGUOUS" option in the call to "allocate()", but some compilers may not support it yet. (many compilers still use F95 or F2003, and only parts of F2008).

Another (less elegant) option would be to allocate a 1D array in the allocate statement in the main program, use it in subroutine calls, and then declare and use the arrays as 3D inside all the routines.

**Comment by komatits** [comment]
It seems Daniel @danielpeter got rid of FORCE_VECTORIZATION; good idea; thus closing this issue.

**Comment by Ram1708** [comment]
What are the computer system specification need to run the SPECFEM3D.
