### ISSUE TITLE
check the units of FORCESOLUTION

### ISSUE THREAD

**Issue by komatits** [geodynamics/specfem3d#842]
On 02/02/2015 03:46 PM, Dominique Turmel wrote:

Hi all!

I am using the specfem3d Cartesian software. I was wondering, and I did not find the answer in the manual or elsewhere, what will be the units when using the FORCESOLUTION?  If I have a factor force source of, say, 1.d15, that means that the source time function will be multiplied by 1d15.  What will be the units of that force?

Thanks a lot!

Dominique Turmel
dominique DOT turmel DOT 1 AT ulaval DOT ca

**Comment by komatits** [comment]
Dear Dominique,

My colleague Alexis Bottero @bottero is currently working on that (making it use standard S.I. units, checking that the seismograms then have the right amplitude compared to the analytical solution in a few test cases, and adding that to the users manual); thus let me cc him.

Thanks,
Dimitri. 
cc @vmont @bencesolymosi

**Comment by komatits** [comment]
cc @EtienneBachmann

**Comment by komatits** [comment]
From Mathias Pilch:

By setting in DATA/Par_file

    USE_FORCE_POINT_SOURCE = .true.

A Gaussian will be used as a source time function, defined in

    src/specfem3D/comp_source_time_function.f90

and

    double precision function comp_source_time_function_gauss(t,hdur)

There, in line 68, stands the definition,

   comp_source_time_function_gauss = exp(-a*t**2) / (sqrt(PI)*hdur_decay)

where a = 1.d0 / (hdur_decay**2) and

hdur_decay = hdur / SOURCE_DECAY_MIMIC_TRIANGLE,

with SOURCE_DECAY_MIMIC_TRIANGLE = 1.628

The normalization factor in front of the exp() is defined so that the area under
the curve is = 1.

If you want the amplitude of the Gaussian to be F_0 in Newton, you have to redefine
comp_source_time_function_gauss to
      comp_source_time_function_gauss = F_0 * exp(-a*t**2).

However, I am still not sure where exactly

    factor force source: 1.d0

in DATA/FORCESOLUTION comes into play. It’s probably acting in the same way as F_0 in the
equation above.

**Comment by EtienneBachmann** [comment]
Hi,

Regarding this gaussian source time function, the use of hdur_decay (hdur_decay = hdur / SOURCE_DECAY_MIMIC_TRIANGLE) makes the central frequency of the gaussian smaller. When I perform gaussian simulation, I have to multiply by around 1.68 to get what I want. I am not sure of the utility of this SOURCE_DECAY_MIMIC_TRIANGLE division.
Aside, in the acoustic case, I am not sure that the current definition of the gaussian pulse, which only has positive values and does not oscillate, makes sense physically. Another definition, such as the matlab function "gmonopuls", might be better.

**Comment by komatits** [comment]
Done! I will commit the changes tomorrow.
