### ISSUE TITLE
How to use conjugate gradient method for model update ?

### ISSUE THREAD

**Issue by yuefeng9330** [geodynamics/specfem3d#914]
Hi all,

In the tomography tool, the program "add_model_iso" use a steep descent method for model update by calling get_sd_direction_iso() in get_sd_direction.f90. I notice there is a subroutine called  get_cg_direction_tiso() in get_cg_direction.f90, which can be used to use conjugate gradient method for transverse isotropic model update. 

Does anyone have changed the code to do conjugate gradient method for isotropic model update? It would be great If we can add the conjugate gradient method for isotropic model update in the tomography tool. Thanks in advance!

**Comment by komatits** [comment]
New tomography tools will be released in a few months (and thus unfortunately we do not maintain the old ones any more).
