### ISSUE TITLE
whay is the xgenerate_databases MPI process creating ranks above 3 evenhough -np is 4? in version 2.0.2

### ISSUE THREAD

**Issue by Bhanutejacds** [geodynamics/specfem3d#999]
Fatal error in PMPI_Isend: Invalid rank, error stack:
PMPI_Isend(161): MPI_Isend(buf=0x9e17d4, count=2797, MPI_INTEGER, dest=4, tag=0, MPI_COMM_WORLD, request=0x65dd04) failed
PMPI_Isend(103): Invalid rank has value 4 but must be nonnegative and less than 4
Fatal error in PMPI_Isend: Invalid rank, error stack:
PMPI_Isend(161): MPI_Isend(buf=0x9d3eb8, count=2797, MPI_INTEGER, dest=5, tag=0, MPI_COMM_WORLD, request=0x65fdf8) failed
PMPI_Isend(103): Invalid rank has value 5 but must be nonnegative and less than 4
Fatal error in PMPI_Isend: Invalid rank, error stack:
PMPI_Isend(161): MPI_Isend(buf=0x9d3eb8, count=2797, MPI_INTEGER, dest=6, tag=0, MPI_COMM_WORLD, request=0x65fdf8) failed
PMPI_Isend(103): Invalid rank has value 6 but must be nonnegative and less than 4
Fatal error in PMPI_Isend: Invalid rank, error stack:
PMPI_Isend(161): MPI_Isend(buf=0x9df224, count=2797, MPI_INTEGER, dest=7, tag=0, MPI_COMM_WORLD, request=0x9eccd4) failed
PMPI_Isend(103): Invalid rank has value 7 but must be nonnegative and less than 4

**Comment by komatits** [comment]
It is an install problem of MPI on your machine or in the scripts you use to start MPI runs.
